# Section 1: Exploratory Data Analysis EDA

## Phase 1: Data Health, Cleaning, Manipulating, Preparing

### 1. Importing Libraries and Loading Data

In [10]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy as sp
import zipfile 
import os
import kagglehub
from dotenv import load_dotenv
print('libraries imported!')

libraries imported!

In [11]:
load_dotenv()
zip_path = os.getenv('ZIP_PATH')
csv_path = os.getenv('CSV_PATH')

if not os.path.exists(csv_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref :
        zip_ref.extractall("data/")
    print('Extraction done!')
else :
    print('zip file already extracted!')

zip file already extracted!

### 2. Initial Data Inspection

In [12]:
df = pd.read_csv(csv_path)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   year                   1000000 non-null  int64
 1   quarter                1000000 non-null  str
 2   company                1000000 non-null  str
 3   industry               1000000 non-null  str
 4   region                 1000000 non-null  str
 5   department             1000000 non-null  str
 6   economic_condition     1000000 non-null  str
 7   work_model             1000000 non-null  str
 8   inflation_rate         1000000 non-null  float64
 9   interest_rate          1000000 non-null  float64
 10  gdp_growth             1000000 non-null  float64
 11  ai_adoption_score      1000000 non-null  int64
 12  automation_level       1000000 non-null  int64
 13  employees_hired        1000000 non-null  int64
 14  layoffs                1000000 non-null  int64
 15  attrition_rate         1000000 non-null  float64
 16  employee_satisfaction  990000 non-null   float64
 17  avg_salary             990000 non-null   float64
 18  revenue_growth         990000 non-null   float64
 19  stock_growth           1000000 non-null  float64
 20  productivity_index     1000000 non-null  float64
 21  innovation_score       1000000 non-null  float64
 22  layoff_risk_score      1000000 non-null  float64
dtypes: float64(11), int64(5), str(7)
memory usage: 175.5 MB

In [13]:
df.describe()

,year,inflation_rate,interest_rate,gdp_growth,ai_adoption_score,automation_level,employees_hired,layoffs,attrition_rate,employee_satisfaction,avg_salary,revenue_growth,stock_growth,productivity_index,innovation_score,layoff_risk_score
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,990000.000000,990000.000000,990000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,2015.501059,4.059324,3.506190,2.997288,28.982024,29.109442,6046.851745,1970.385495,15.946582,65.070168,80261.371138,4.956334,4.976125,68.652561,71.315736,36.224992
std,6.347227,1.883837,1.488236,2.500446,20.988087,22.249484,3437.105021,1670.457790,5.986126,12.825780,29744.848938,11.925981,16.926276,11.186697,15.451910,29.373006
min,2005.000000,1.000000,0.000000,-8.000000,0.000000,0.000000,100.000000,0.000000,2.000000,1.000000,30000.000000,-40.000000,-60.000000,6.300000,1.000000,0.000000
25%,2010.000000,2.650000,2.490000,1.310000,13.000000,11.000000,3071.000000,849.000000,11.890000,57.200000,57847.000000,-3.000000,-6.400000,61.300000,60.800000,11.400000
50%,2016.000000,4.000000,3.500000,3.000000,25.000000,25.000000,6040.000000,1698.000000,15.670000,65.600000,78095.000000,5.060000,5.040000,68.700000,71.500000,32.100000
75%,2021.000000,5.350000,4.510000,4.680000,42.000000,43.000000,9025.000000,2549.000000,19.620000,73.700000,100737.000000,13.020000,16.410000,76.200000,82.300000,54.200000
max,2026.000000,14.310000,10.800000,12.000000,100.000000,100.000000,11999.000000,16077.000000,45.000000,100.000000,217594.000000,70.250000,90.930000,100.000000,100.000000,100.000000

### 3. Checking for Duplicates

In [14]:
df[df.duplicated()]

Empty DataFrame
Columns: [year, quarter, company, industry, region, department, economic_condition, work_model, inflation_rate, interest_rate, gdp_growth, ai_adoption_score, automation_level, employees_hired, layoffs, attrition_rate, employee_satisfaction, avg_salary, revenue_growth, stock_growth, productivity_index, innovation_score, layoff_risk_score]
Index: []

[0 rows x 23 columns]

### 4. Variable Categorization (Discrete, Continuous, Categorical)

In [15]:
discrete_variables = []
continuous_variables = []
categorical_variables = []

for var in df.columns :
    #variables
    col = df[var]
    unique_values = col.unique().tolist()
    distinct = len(unique_values)

    #conditions
    is_decimal = (col.dtype == 'float64')
    is_int = (col.dtype == 'int64')
    is_string = (col.dtype == 'str')

    if is_int or is_decimal :
        fractional_part_not_null = ((col.dropna() % 1 != 0).any())
        fractional_part_is_null = ((col.dropna() % 1 == 0).all())

    #logic
    if is_string :
        categorical_variables.append(var)

    elif (is_int or (is_decimal and fractional_part_is_null)) and (distinct < 10):
        discrete_variables.append(var)

    elif ((is_int or (is_decimal and fractional_part_is_null)) and distinct >= 10) or (is_decimal and fractional_part_not_null):
        continuous_variables.append(var)
    
        
    else:
        print(var, "is unknown")
categories = ['discrete', 'continuous', 'categorical']
for cat in categories :
    liste = globals()[f'{cat}_variables']
    if len(liste) == 0 :
        print(f'There is no {cat.capitalize()} variables in this dataframe')
    else : 
        print(f"{cat.capitalize()} variables :\n{liste}\n")

There is no Discrete variables in this dataframe
Continuous variables :
['year', 'inflation_rate', 'interest_rate', 'gdp_growth', 'ai_adoption_score', 'automation_level', 'employees_hired', 'layoffs', 'attrition_rate', 'employee_satisfaction', 'avg_salary', 'revenue_growth', 'stock_growth', 'productivity_index', 'innovation_score', 'layoff_risk_score']

Categorical variables :
['quarter', 'company', 'industry', 'region', 'department', 'economic_condition', 'work_model']

### 5. Checking Unique Values

In [16]:
dict = {}
for col in df.columns :
    if df[col].dtype == 'str' or 'year' in col.lower():
        unique_values = df[col].unique()\
                                .tolist()
        unique_values.sort()
        dict[col] = unique_values
        print(f'For column "{col.upper()}" unique values are :\n{dict[col]}\n')

For column "YEAR" unique values are :
[2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]

For column "QUARTER" unique values are :
['Q1', 'Q2', 'Q3', 'Q4']

For column "COMPANY" unique values are :
['ApexAI', 'ByteFusion', 'CloudSphere', 'CyberWave', 'DataNest', 'FutureGrid', 'NeuroLink Systems', 'PixelCore', 'QuantumEdge', 'TechNova']

For column "INDUSTRY" unique values are :
['AI', 'Cloud Computing', 'Cybersecurity', 'Data Analytics', 'E-Commerce', 'FinTech', 'Gaming', 'Software']

For column "REGION" unique values are :
['Asia-Pacific', 'Europe', 'Middle East', 'North America', 'South America']

For column "DEPARTMENT" unique values are :
['Data Science', 'Engineering', 'Finance', 'HR', 'Marketing', 'Operations', 'Product', 'Sales']

For column "ECONOMIC_CONDITION" unique values are :
['AI Boom', 'Growth', 'Pandemic', 'Recession', 'Slowdown', 'Stable']

For column "WORK_MODEL" unique values are :
['Hybrid', 'Onsite', 'Remote']

### 6. Data Type Optimization

In [17]:
for col in categorical_variables:
    df[col] = df[col].astype('category')
print("All categorical variables have dtype 'category' instead of 'string'")

All categorical variables have dtype 'category' instead of 'string'

### 7. Handling Missing Values (Imputation)

In [18]:
df['avg_salary'] = df['avg_salary'].fillna(df.groupby(['department', 'region'])['avg_salary'].transform('median'))
df['revenue_growth'] = df['revenue_growth'].fillna(df.groupby(['industry', 'year'])['revenue_growth'].transform('median'))
df['employee_satisfaction'] = df['employee_satisfaction'].fillna(df.groupby(['department', 'company'])['employee_satisfaction'].transform('median'))
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   year                   1000000 non-null  int64
 1   quarter                1000000 non-null  category
 2   company                1000000 non-null  category
 3   industry               1000000 non-null  category
 4   region                 1000000 non-null  category
 5   department             1000000 non-null  category
 6   economic_condition     1000000 non-null  category
 7   work_model             1000000 non-null  category
 8   inflation_rate         1000000 non-null  float64
 9   interest_rate          1000000 non-null  float64
 10  gdp_growth             1000000 non-null  float64
 11  ai_adoption_score      1000000 non-null  int64
 12  automation_level       1000000 non-null  int64
 13  employees_hired        1000000 non-null  int64
 14  layoffs                1000000 non-null  int64
 15  attrition_rate         1000000 non-null  float64
 16  employee_satisfaction  1000000 non-null  float64
 17  avg_salary             1000000 non-null  float64
 18  revenue_growth         1000000 non-null  float64
 19  stock_growth           1000000 non-null  float64
 20  productivity_index     1000000 non-null  float64
 21  innovation_score       1000000 non-null  float64
 22  layoff_risk_score      1000000 non-null  float64
dtypes: category(7), float64(11), int64(5)
memory usage: 128.7 MB

## Phase 2: Visualizing Data using Seaborn and Matplotlib

## Phase 3: Statistics and Statistical Tests