# Phase 1: Environment Setup
### 1.1 Library Imports
Loading required data science and visualization libraries.

In [32]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pylab as plt
import scipy as sp
import sklearn as sk
print('done!')

done!

# Phase 2: Processing Playlists Dimension (`dim_playlists`)
### 2.1 Data Loading & Initial Inspection
Loading the raw playlists dataset and viewing schema.

In [33]:
df = pd.read_csv('dim_playlists.csv')
df.head()

,playlist_id,playlist_name,published_at,total_videos
0,PLmur3Z0Afau49M9Qhc9ljxktYH58szH87,AI Architects,2026-04-02T16:07:19.491746Z,3
1,PLmur3Z0Afau6EJFQNsmCd0badJOW7vN9J,The Inspiration Lab,2025-11-20T19:00:23.715012Z,3
2,PLmur3Z0Afau6_ebbQaBXqwocwVN7y0_6y,Well Spent,2025-11-14T23:08:40.000088Z,2
3,PLmur3Z0Afau728_hvIL3xdqygK6lj27Eq,War Journal,2025-11-11T22:19:17.741199Z,0
4,PLmur3Z0Afau6OyqRXF96t97YxY-dYfv3L,Well Spent | The Podcast,2025-10-31T20:00:43.357812Z,2

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   playlist_id    51 non-null     object
 1   playlist_name  51 non-null     object
 2   published_at   51 non-null     object
 3   total_videos   51 non-null     int64
dtypes: int64(1), object(3)
memory usage: 1.7+ KB

### 2.2 Data Transformation: Datetime Parsing
Extracting Date and Time components from the ISO 8601 timestamp.

In [35]:
df['published_at'] = pd.to_datetime(df['published_at'])
df['published_date'] = df['published_at'].dt.date
df['published_date'] = pd.to_datetime(df['published_date'])
df['published_time'] = df['published_at'].dt.time
df.drop(columns=['published_at'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   playlist_id     51 non-null     object
 1   playlist_name   51 non-null     object
 2   total_videos    51 non-null     int64
 3   published_date  51 non-null     datetime64[ns]
 4   published_time  51 non-null     object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 2.1+ KB

# Phase 3: Processing Videos Dimension (`dim_videos`)
### 3.1 Data Loading & Shape Verification
Loading the raw videos dataset for dimensional modeling.

In [36]:
df_dim_vids = pd.read_csv('dim_videos.csv') 
df_dim_vids.shape

(7841, 26)

### 3.2 Data Transformation: Datetimes & Time Durations
Separating publish dates and converting video durations from seconds to a standard format.

In [37]:
df_dim_vids['published_at'] = pd.to_datetime(df_dim_vids['published_at'])
df_dim_vids['published_date']=df_dim_vids['published_at'].dt.date
df_dim_vids['published_date'] = pd.to_datetime(df_dim_vids['published_date'])
df_dim_vids['published_time']=df_dim_vids['published_at'].dt.time
df_dim_vids.drop(columns = ['published_at'], inplace = True)
df_dim_vids.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7841 entries, 0 to 7840
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   video_id               7841 non-null   object
 1   title                  7841 non-null   object
 2   duration_seconds       7841 non-null   int64
 3   view_count             7841 non-null   int64
 4   like_count             7841 non-null   int64
 5   comment_count          7841 non-null   int64
 6   tags                   7702 non-null   object
 7   is_hd                  7841 non-null   bool
 8   licensed_content       7841 non-null   bool
 9   made_for_kids          7841 non-null   bool
 10  audio_language         7841 non-null   object
 11  region_allowed         0 non-null      float64
 12  region_blocked         0 non-null      float64
 13  content_rating         7841 non-null   object
 14  privacy_status         7841 non-null   object
 15  license                7841 non-null   object
 16  embeddable             7841 non-null   bool
 17  public_stats_viewable  7841 non-null   bool
 18  topic_categories       6783 non-null   object
 19  recording_date         8 non-null      object
 20  latitude               0 non-null      float64
 21  longitude              0 non-null      float64
 22  has_captions           7841 non-null   bool
 23  primary_hashtag        1741 non-null   object
 24  content_type           7841 non-null   object
 25  published_date         7841 non-null   datetime64[ns]
 26  published_time         7841 non-null   object
dtypes: bool(6), datetime64[ns](1), float64(4), int64(4), object(12)
memory usage: 1.3+ MB

In [38]:
df_dim_vids['duration'] = pd.to_datetime(df_dim_vids['duration_seconds'], unit='s').dt.strftime('%H:%M:%S')

### 3.3 Feature Selection: Dropping Irrelevant Columns
Removing geospatial and blocked region metadata not needed for our current analysis.

In [39]:
df_dim_vids.drop(columns=['region_allowed',
                          'region_blocked', 
                          'latitude', 
                          'longitude', 
                          'recording_date'],
                           inplace = True)
df_dim_vids.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7841 entries, 0 to 7840
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   video_id               7841 non-null   object
 1   title                  7841 non-null   object
 2   duration_seconds       7841 non-null   int64
 3   view_count             7841 non-null   int64
 4   like_count             7841 non-null   int64
 5   comment_count          7841 non-null   int64
 6   tags                   7702 non-null   object
 7   is_hd                  7841 non-null   bool
 8   licensed_content       7841 non-null   bool
 9   made_for_kids          7841 non-null   bool
 10  audio_language         7841 non-null   object
 11  content_rating         7841 non-null   object
 12  privacy_status         7841 non-null   object
 13  license                7841 non-null   object
 14  embeddable             7841 non-null   bool
 15  public_stats_viewable  7841 non-null   bool
 16  topic_categories       6783 non-null   object
 17  has_captions           7841 non-null   bool
 18  primary_hashtag        1741 non-null   object
 19  content_type           7841 non-null   object
 20  published_date         7841 non-null   datetime64[ns]
 21  published_time         7841 non-null   object
 22  duration               7841 non-null   object
dtypes: bool(6), datetime64[ns](1), int64(4), object(12)
memory usage: 1.1+ MB

### 3.4 Data Profiling: Duplicates Assessment
Checking for duplicated records in the API payload.

In [40]:
df_dim_vids.duplicated().sum()

np.int64(0)

### 3.5 Data Cleaning: Standardizing Categorical Features
Extracting nested dictionary values (like `ytAgeRestricted`) and standardizing language codes.

In [41]:
df_dim_vids["content_rating"].unique().tolist()

['{}', "{'ytRating': 'ytAgeRestricted'}"]

In [42]:
df_dim_vids[df_dim_vids['content_rating'] == "{'ytRating': 'ytAgeRestricted'}"]

,video_id,title,duration_seconds,view_count,like_count,comment_count,tags,is_hd,licensed_content,made_for_kids,...,license,embeddable,public_stats_viewable,topic_categories,has_captions,primary_hashtag,content_type,published_date,published_time,duration
2037,MzU_8jQ_4zs,This farmer uses gasoline to make coca paste #...,59,645920,20337,451,"Business Insider, Business News",True,True,False,...,youtube,True,True,https://en.wikipedia.org/wiki/Lifestyle_(socio...,False,NaN,Short,2023-08-25,16:18:52,00:00:59
2334,QxbkaqfL_bI,Why People Risk Their Lives To Kill Bulls That...,726,212509,2520,1123,"Insider, News, bull fighting, spain, risky bus...",True,True,False,...,youtube,True,True,https://en.wikipedia.org/wiki/Society,False,#Bulls,Standard Video,2023-02-04,17:00:28,00:12:06
2433,SD66p3XE_TE,Every Piece Of Gear In A US Army Combat Medic'...,792,156795,3890,233,"Business Insider, Business News, Loadout, Army...",True,True,False,...,youtube,True,True,"https://en.wikipedia.org/wiki/Military, https:...",True,#Army,Standard Video,2022-11-10,16:00:13,00:13:12
2521,XM94wRqgMes,Biggest challenges for the #cannabis industry ...,43,47708,1845,59,"Business Insider, Business News",True,True,False,...,youtube,True,True,https://en.wikipedia.org/wiki/Lifestyle_(socio...,False,NaN,Short,2022-08-03,18:00:10,00:00:43
2550,gDEVO02KIa0,How Bread Became Unaffordable Across The World...,701,1984786,22969,3173,"Business Insider, Business News, Big Business,...",True,True,False,...,youtube,True,True,https://en.wikipedia.org/wiki/Society,True,#GrainShortage,Standard Video,2022-06-16,21:00:33,00:11:41
2987,uadGTl8Hwss,Why Online Sex Work Has Risen During The Pandemic,411,111613,561,115,"Insider, News, sex, sex work, only fans, femal...",True,True,False,...,youtube,True,True,https://en.wikipedia.org/wiki/Lifestyle_(socio...,True,#Sex,Standard Video,2020-08-15,16:00:13,00:06:51
3041,wTLAfT4w1zQ,What It's Like Being A Funeral Director During...,346,385415,5474,478,"Business Insider, Business News, funerals, cor...",True,True,False,...,youtube,True,True,"https://en.wikipedia.org/wiki/Health, https://...",True,#Coronavirus,Standard Video,2020-04-07,21:28:46,00:05:46
3107,xvY_TcBn2Gs,Why Full-Spectrum CBD Oil is So Expensive | So...,397,344701,6133,530,"Business News, CBD, CBD oil, Business Insider,...",True,True,False,...,youtube,True,True,https://en.wikipedia.org/wiki/Health,True,#CBD,Standard Video,2019-12-21,16:00:08,00:06:37
3184,xGYA5hx6wP4,What It's Like Inside A Canadian Marijuana Gre...,208,399162,6452,649,"Business Insider, Business News, cannabis, mar...",True,True,False,...,youtube,True,True,https://en.wikipedia.org/wiki/Society,False,#Canada,Standard Video,2019-09-05,15:00:10,00:03:28
3690,uy-VZHqwWNM,The Racist Origins of Marijuana Prohibition,402,102475,2540,377,"Business Insider, Cannabis, Marijuana, Laws, L...",True,True,False,...,youtube,True,True,"https://en.wikipedia.org/wiki/Politics, https:...",True,NaN,Standard Video,2018-03-01,15:31:17,00:06:42
3876,VsFzSecmEck,Baby born with heart outside her body becomes ...,106,43630,140,13,"Europe, Medicine, Operation, BI, Surgery, Orig...",True,True,False,...,youtube,True,True,https://en.wikipedia.org/wiki/Health,False,NaN,Standard Video,2017-12-13,12:36:34,00:01:46
5754,8fCu2wGl2U8,Two Ukrainian politicians brawl,88,77700,460,80,"Business Insider, Politics, Ukraine, Russia, I...",True,True,False,...,youtube,True,True,"https://en.wikipedia.org/wiki/Politics, https:...",False,NaN,Standard Video,2016-11-18,01:00:00,00:01:28
6087,6dLnPkPe67I,What a DEA agent did when asked to try drugs,73,2972822,21828,2513,"Business Insider, DEA, Drugs, Cartels, Drug tr...",True,True,False,...,youtube,True,True,"https://en.wikipedia.org/wiki/Health, https://...",False,NaN,Standard Video,2016-10-18,21:30:01,00:01:13
7377,nJzeuH2Kj3c,Mark Cuban Only Has 13 Apps On His Phone,66,5524,33,3,"Mark Cuban (Sport Club Owner), Apps, Applicati...",True,True,False,...,youtube,True,True,https://en.wikipedia.org/wiki/Business,False,NaN,Standard Video,2014-04-05,17:30:01,00:01:06
7457,ig4GThhvsgo,How To Kill A Chicken For Dinner,85,549033,1588,570,"Chicken (Organism Classification), Chicken Mea...",True,True,False,...,youtube,True,True,https://en.wikipedia.org/wiki/Lifestyle_(socio...,False,NaN,Standard Video,2013-12-27,18:00:02,00:01:25

In [43]:

df_dim_vids['content_rating'].replace({'{}' : 'not age-restricted', "{'ytRating': 'ytAgeRestricted'}" : "age-restricted" }, inplace = True)

In [44]:
for col in df_dim_vids.columns :
    if df_dim_vids[col].dtype == 'object':
        name = f'{col}_uniques'
        liste = df_dim_vids[col].unique().tolist()
        print(f"{name} : {liste}\n")

video_id_uniques : ['WruHZnB_srw', 'BDqhOhr-orw', 'r3p0R9dlKww', 'Gv8mItBLZ5Y', 'dKoIepQtPO8', 'dp5QFSjloNM', '1Qp1yaSpfx8', 'TM47c__WOfQ', 'bG6bXMhy0Ps', 'x3wVNJlem7U', 'rWSL0v-rmak', 'OCGQIAk8zIM', 'PJqh69mNTtM', '_rcRea7DG10', 'g4oIYbI9tog', 'sA_U4DhYmbc', 'QQvvO8Mqk1w', 'yqBwFlECOXc', 'QG6cEqow99Y', 'KmE6OPhpLjw', 'GtjkUge5aew', 'CngqU51dsJU', 's80mBDNJ5lo', 'oslN3LtaBqI', 'SIjMGjKA9Rs', 'bzDonR6Pfo4', 'I6LPhS7yH-c', 'Pf8eNoGqut0', '9JLKfP5uJ9E', 'rCjtlBmKkMU', 'shyDrSrHcwo', 'ma5IsOYGxrs', 'pOi_AQ9F_Mo', '2-s8P58EwTY', 'ZyGH4eUXAX4', 'nD0bNdRu0w8', 'KH6O-MuUdB8', 'GG7j5PqX4UY', 'yxF_RnU400k', 'dfN3BQt6i98', 'ZCs_Z86qvYU', 'jCkvBQWhrNA', 'ENRrTJdlyg8', 'lRUS-7P0a4k', 'uGkwc-JWdYw', 'ydqkCytz9GI', 'BsEfPvIrVCc', 'RljBVCnt9AQ', '5MIn6v9h0oQ', 'Qytqug0QgKg', '1d_KSbE2LX8', 'aMtaVPjiOqw', 'NwTg6HjkEgQ', 'C3VjFb1_ct4', 'DUgesPqAztc', 'jvdo-c0Pa1M', 'vSYgZG9UNN4', '1YDQiiBKgTQ', '9djOjC1Uszc', 'FfqVuyF8wnY', 'ULPQZsj0J2Y', 'hohnMVXn91E', 'HjSQ10zDB0k', 'T_RbZxmafrE', 'bvqzzusB-_M', '6_aKBUfY2Yc', 'LyeOo_muleM', '9byGejq8Uko', 'I6q1AUJWAUk', 'WgxrMaHvs-Q', 'JBBZyYBvtxs', 'iCYg96L6GWU', '715dmYhlF2M', 'GbliZCntNXU', 'HF-pV_7XRyE', '0MOwdS1tU7I', 'qVJZMZB4NTY', 'liJHbQN-N4A', 'bxVvA8SfJpc', 'sKQbArT36AU', 'NYcv1ZFZTDI', 'k9e6ejg3UIk', 'f7usxflVNcQ', 'Mnv6y3MVVKc', 'dHjvgtu0PXw', 'jDoXsHpexZs', 'mceHQqvOIJY', 'hqAgQadwDpc', 'ebx7JyeTxYc', 'a557pgwd6MU', 'KNWDmYhyA_I', 'BpfnV05fXrc', 'vV4Rux4LRds', 'lOha9RQQtAo', 'Ft8TGsaVs7s', '3Vld5h98O90', 'T9AQJj2Pquo', 'Kcq0tjmvGOs', 'J96c34NHhls', 'FhqUKeXutuc', 'RfKlcttNBG0', '47z7MGHdyQw', '9LRuaQ4594c', 'bTXr5-jTcbg', 'l7SsCzP0als', 'YvtPHoQE4os', 'aOMyRHP2crU', 'zkH6BifgaE4', 'Y3K8Rc8FR2M', '66iCIfoCIVA', 'qEMtQjcjIIc', '_CTu2FMk8l4', 'Zp3Ajt5U6qA', '14mEq7iUDjc', 'o5opXRMhcyg', 'kSUjDfNAiuU', 'jUH94mP3Yas', 'eo06Z1Vea9c', 'Af72fKffNs0', 'zTa4_-oSMGQ', 'kddthyR48PM', '5Y_5MozNiZk', '7-MII1LYkpo', 'tyoTyquAUis', 'ZReJpDphqQQ', 'IIeOvm_Cv6M', 'cEquo_eCMWI', 'J5fbNMGggDE', 'l-KpNxmDOio', 'ORzslauiUik', 'O5pxmhXbGME', 'c6lryBSrSAQ', 'bkTrtv5nVmc', '37uoYrCxsDs', 'RxcqWG2ah9k', '3tWA_hgNv1w', 'I7OhjHyAUbs', 'n3YcToYHCB4', 'jGGQ-UxVjCU', 'ncBXvkIWihM', 'H_dLm5u0mQw', '4Kz0CdFVGCI', 'pQAmvlgt9CE', 'yKeYKNl4RSc', '6Gyghgj7RhI', 'uxe4OrNTU2c', '0mdzlfQQSl8', 'lJYlTAXn4t0', 'TXdVyunArDk', 'f-bsab93UZ0', '6yqLaG14qB0', 'E4HECt5orOA', '5t_cfBAcTDc', 'GQPg_JYcgt4', 'ZMFlXabFXBU', '5wB_wgOsR2g', '6RgJP1wIuls', '-_RBZfd4ZBg', 'Gu8IXdzoulQ', 'X05BsYqZSdg', 'So46F7v2jgk', 'Qt3KppJNDtE', 'Dw5OETIQH0g', 'VtltG-fQBzw', 'mo95GRqzEKw', 'urlKiE7Vpxk', '1_YDTGnir4g', 'Tqo2hMcLmt0', 'W8AzYWnrSmQ', 'HLngxE6C4v8', 'R_MtUHR1Pxo', 'L-1onPXTTyE', 'BjAjviFHAMo', 'qCZK46Potp0', 'iF-EPsbNvqo', 'VWH1AoZTBxc', 'ok_2fqku9ik', 'A0W4igjZKpI', 'AbVuU_fiPiw', 'nLzQaj4__7Y', '3xGA-QzW7ZE', '3RNiQ4EaTJM', 'U9lidC1C8xg', 'uxyd6tAI-ZU', 'jDjZaSdwJ5E', 'PCxkI49hrwo', 'c89_HXgWTQE', '8adECUCmP90', 'F38aEkyzfas', 'flfGrcsjVus', 'SbSK7EBlB10', 'QF6fDItt-Jw', 'v-8R55oyYfs', 'xC-J9GEzkW8', 'i7PqWY57-po', 'oYEGRC76mV4', '_8vNujOWXR8', 'z1Wyro2vXgU', 'y9SDUt5wvak', 'bC6S9ZuR17Y', 'Ss5H62LDiMg', 'm-umNBbDK1s', 'wgsh7VTJALY', 's-Ac6CTmoMQ', 'qji1mbzo4wU', 'swgm5dDAcMU', 'Asc_TrJllyo', 'xUzIqdEPC-k', 'dGRLAYW1QHQ', 'pwFUrE2YWjo', 'S6i2uHkj8LM', 'P1Xxz9j2Cgo', 'GDuq-A0djqU', 'mm6UJ6HjwXg', 'GwugYT9zB_4', 'XzVqbHxw9ks', 'yptrdzTTDSk', 'vW7qhbuDgS8', '5Cv9qU-TfqI', 's4679CUuMqo', 'guCkWXZlQfI', '8dcZA3IfDdg', '8AKn-zJMIwY', 'NZXfXmRYbQY', 'ufnAA6KG4_k', 'vNizX0HIqRA', '6V46scOHnA4', 'yFX_rERVjzc', 'ZyRmGNCZd5A', 'vFigtFoMObg', 'maTntMnYAMA', 'sD55v2WYUAY', 'z9Pl4GIKQdM', '1zuSeOznrDM', 'Qq0qb4zRzcI', 'FaV6n0tGeoQ', 'wfXV66nscC4', '_1oVKuG3BpI', 'rofyxAwDQAU', '5RgSuHeM5wc', '8mPUBuTtz94', 'Uwe4weUl7RA', 'b9orWxlPNAo', 'z0M8QchQGXI', 'yK3_RriFPuc', 'ZxRd8rI9o20', 'elrUpoc78SU', 'uEISc57caL8', 'jij6YLMEhoY', 'd0s_s5GZWi8', '8GW-TdHbLBU', 'n1P0U3uV7ko', 'zOd01sLlDj4', 'YmdoYptHGyk', '-0GPWaMBiy0', 'DLAZX4HOcUs', 'rpMnfBcWdO8', 'nbBNt1UhF6Q', 'Jb6cWp76Np8', '7q9KYJNu-R8', 'iJKEg4y-dRM', 'KMUZAUF7-ok', 'k6SY4Swn0Sw', '9wlEM7VdRjE', '8MygYVp9AMI', '8_AwER_bLEg', 'rskbKTbBD-E', 'LBqeiB7jx-I', 'suyfDsM8YOY', '9qiJLPkVY7Y', 'cHS_6uISd2I', 'vy1JPpTlOdo', 'YYxUhhwWbOk', 'nqn9Bzoa04E', 'oTV2a5fjN0c', 'XPfTRI4sazM', 'pk0Zm_xpk3c', 'OlFClfAw9hk', 'xiY3tnyTzpM', 'Z9xCK-AhpAs', 'Y6sEDYZMYec', 'lfulsZ3flGI', 'Lr1gWNnIPLo', 'nDzIevSAczY', 'h5CM_5VA2PI', 'sN1AVSZyFbY', 'LL7Kt6gXuXY', 'wuTTamqrHWE', 'vOMnrcYG8O4', 'popSWtKu33Q', 'jNxiE4zlgLw', 'a0nrXBJ0-0k', '9V0Uvxp_oXk', 'QCCxc_uQJ40', 'wQMCdDTkIks', '_qfxaeL76tM', 'nBjgngg6_bE', 'hG2PgyuBiYs', 'a173gcrUl4Y', 'YDSwb4DqD90', 'B-lF-Bev3Vg', '2e61nFzLKYo', 'O1-WQhtcmh8', 'hP5lJ3nlyJw', '_6WnF4Rbhjw', 'nDGD9hmWtiA', 'ruYCVuq0aCY', 'HHQHQkz4Mx4', 'G17MaGbUieo', 'tN-6pT7nsx0', 'Q-8nM3ydZw4', '62GkaZdg6Hw', 'sPZebkT92Qk', 'Btq51euV1HM', '_K5LhLUzYuc', 'bXp3ZdPzIFQ', 'o05t0yHfsqU', 'bBEB_HB9bsQ', 'X-FKuKtO8n0', 'KsetTg2Y2oo', 'NIDLendPlec', 'brJ2In0kN50', '16Nrq1EXKdI', 'Me-G1XklA0s', '9DaEmvKWsEA', 'CSSg-jYH4L4', 'yWXnfY_De8M', 'wb5lvJ1KfrU', 'wBuOv5Qq_Qk', 'ZmzqQ-aPv4k', 'NrRub6v4vEk', 'Mr8FCpOm7Lc', '8zaDExHamSI', 'nT0aZ3-ftdY', 'IrRmgAyQBnM', 'BbkvQSwVExs', 'veNBSwR_9mM', 'YnmpMJH5cr8', 'f4CuHjhvNE8', 'u1w60-USuSM', '4dwe5wewSmU', 'snc4-aFo8Ys', 'kMK78kboyp8', 'sf4SmfywpoQ', 'iigq57akfaQ', 'Fw54dW2Rlmc', 'n66lHAF-jXw', 'I9cOuxq8f60', 'UA7Ho0rcABo', 'XaDdUIg-mCk', 'v-82Lg1rTMs', 'h7HfKejfqcE', 'L9W-Wz5DUuk', 'o2Ht3c0Sdyk', '6ukcVg5hiks', '3AacqRQ002w', 'P7q73-d6Yk4', 'jXZaBv3po-4', 'J5ICLh_TkWM', 'Yc827HubVjY', 'iwdN94CL8Y0', 'i_HOGsV4JIo', '57qSDw9G2lI', 'h9nVYFLr-JM', 'Qq-Guy0qOPg', 'LoCYgZeHkWc', 'ZDKRT5JQewg', '5iBPuchwb4E', 'U-X8w2q6YqI', '_XvnvCeiozo', 'iKnZ51uBs30', 'ZPRgsJF70Lw', 'rBIEmqb9vmw', 'cBNruRw2zA4', 'aUjTmYa0xKQ', 'RItnli0kAX4', '68sV8Z05M4c', 'vdLZMgXHvYQ', 'hXYa4-yXp4s', 'LQlGuahgCHk', 'PvYI-zHwI4k', '9Tjwi93QtvA', '5Vn6OxMX0o8', 'YXeeKOYn6sM', 'pP-TQwDOGko', 'SkuJIbazkkM', 'ultPMuBnS9k', 'ioAmrgPrMYY', 'pHwQj4N_vF8', 'HCsPPQ2V-yM', 'l6gd7yec6F0', 'L7D9U3d5ZSI', 'Kt7XKGhtT7Q', '5NOumvDXw5w', '3fT0VYV14ag', '_m6ZYbqXbYw', 'BwZT5ePI7ec', 'x6k5XrNwwyM', 'CbtbN4dyfwE', '7aIRFYzLV9M', 'bVuQfXje8KQ', 'HhsZ0s3KXAQ', 'GOPr7N6BDxA', 'KAdSNaknrUE', '9Bn6eWGoe4w', 'blMRs6Wh-G0', 'v828JFvtupI', 'B_9UjwUavGk', '8Fhzz4c-a4I', '9gED4RFMOZM', 'SNGiWla9cIE', '7n0pr3LKphA', 'jGi1F43993U', '5JRf5CrGB5I', '2RgzOYNdnLE', 'fv_dx-lz8N8', 'Ap-gNRXQ5aQ', '_bFtnBBOIVs', 'r3lJQexApnc', 'e6R1KlxIHTo', 'IlnXLTqk5pE', 'Y6doBVxZVAs', 'YTUGNBU7IaI', 'XoTZItCldn4', 'BJnBBBnFKGg', 'z9OicXWc20U', 'lfY4xXfoJ8U', 'e-ABv-PubWk', 'S4lqW3audrQ', 'zV9v0RIE-iI', '2DxWimticZ8', 'cC4Pm8NS4CA', 'q0WAOgM9Aq8', 'oSiubafYVfU', 'lvvXYdKLJTA', 'Eqj7huV2N7E', 'KFPJ-k1tSiw', 'Lq-qUf1XGR0', 'bn2DXdxlgvg', 'sBBhLjOQL5k', 'diBS0VfVcbs', 'oAGx9HqGh3s', 'Wz3IPIQ28OI', 'DCw5qO6cQec', 'pe9t6sAWFXo', 'm7BdbqoRUCw', '55dMN4IIJ0g', 'l_TbfGEPtsQ', 'E8wjQAQyUgo', 'vraoo9SVNBg', '5ls8jPE5Tc0', 'TnBL8QM8BRw', 'ovaWAcTtbxE', '6BT9odWipq8', 'TTCDLykCk5I', 'M7h12QZC1tE', 't-8TDOFqkQA', 'lkJcodTB2xc', '9vfjze1ddS0', '4iY9nZHUr58', '2qbQHWsm7Do', 'aoptVvldIQE', 'EQvJ0hUXpGQ', 'aJ6kKEnRL7U', 'iiy25Q15BkE', 'c8hq5MsROJA', '5uA73J3jhQg', 'gzoY27hzOmU', 'xnW-byAy-eI', 'BSAMHp9Dcc0', 'HB4tp1lgx6M', 'XZfYXdOUQBc', 'Bba-ojcGPK4', 'mucmpKIbZCQ', 'ER8Cz4-zFQo', '-vKvS9tGzvA', 's7WZQ2kwz8w', 'cnPb6hLwkws', 'EmjEDy40hrQ', 'VyCtgTQWe8Y', 'vni148KpCx8', 'zW_c-4N-0KU', 'LRVuZ5s-r4I', 'w81PTW2nxoo', 'NF84LtM8iho', 'zOjxqgZULOc', 'VZ4HY6fGlcs', 'MPS0PMMSRnU', 'djIGZDvXXPg', '1VEHfoHxlIs', '6pzLhWCxH_g', '6qGjA4pam7g', '_ctDIlxGGHw', '1Kld0XFi-w0', '8BRHNC1IKuw', 'YW9FTIeBszw', '8d5p0_HQ41E', 'h1k3mLhhMmA', 'yg3n0hYg-zU', 'IeXGxUyN09c', '0qjUK5XmISM', '3l2uJQbbTkE', 'LgUd-4r-Nks', 'gyamCFp-q0o', 'E7wZGH52LYc', '-7BSJ_UmH1g', 'Z3rOdV4IoFc', 'pMC2MfKc4b0', '1Lo4kg51G1s', 'iEYsdIO7u7M', 'G98EREdOCT0', 'mh9RtpZPpVo', 'MZWAmty3toQ', 'ry_yeJ2CgSk', '1hiULacZEoY', '2omZgA07NsI', 'Mn2wSBBQXe0', 'fuAo5yNgUE0', 'ddxHzoCCxOI', 'tFgC7TwuAHU', 'qci1agy-j5I', 'CHQZPmISE4A', '70B0a_DDoSw', 'SApiC0oea0c', 'HyGBemaOZnQ', 'EzZk3OkGnsM', '9jISoQGdh5E', 'JfRshktzfJM', 'YfiaVHdmUoY', '-z6s4CepwnQ', 'm5GTkSK14Us', 'UNyY8owMCeE', 'nXGNDeUyRwA', 'q5ezbsiKHWQ', 'Pe2_5vOSF6E', 'D_LbhfGNHs8', '3QJ1X22eom8', 'bzXiIO4ZzWM', 'EOcW5uwcvm8', 'muKHML94YwI', 'a2G3jyqXhfY', 'C9LJTd6pQL4', 'I2BBJjFKjkU', 'fCbRQAQGWHo', 'GBt1baOWyiM', '48JVq4g_lEg', 'YmcAz68nsDM', 'o5isWP9Vjco', '1CCShSBGVLQ', 'gGV_wfRTJwo', 'Rx6fXUht4eE', 'CB_6kPtpVg8', 'Dgk9qZxZTOw', 'dJZn5RAMaYQ', '21NYmmv8iY8', '7rEzhCwPhqc', '0ApanP65Vcc', 'Ji7OVnUCjnA', '8H1OxHuzK-s', 'g1YmEjkIplA', 'a8iZyVGc_F0', 'tw_qv0n2xUA', 'RCocaLOjhEc', 'aR2AhZhCs38', 'K6FvIiOsS1o', 'RRWDH91p0Ng', 'zL1AVDcacyI', 'pYuaSKPN0mE', 'ORrQBi5dgM0', 'BRAwxNVNAxA', 'mexnaJn-Y5s', 'HRM3W2FVGQY', 'f9eIMQ_4J2A', 'MUY6aTTLvZg', '3KfLNa1xPzQ', 'cLSDTTEa8fs', '0FWy-Q7IPco', 'PxTEt6_MnFk', 'CYo2QX6cvZo', 'xWOCxtfN4js', 'WJhqu5_HzBU', '_zxtNOUKc3E', 'ftuCHNTzJzk', '2rFX57FFYvQ', 'KqSBoFXee2M', 'jO8C8U07YEQ', 'O73aCOuJrlw', 'MEG9c-Q3sKg', 'rJiEzY-VC4E', 'h2YKBp4JUQo', 'q1TYjRtymUE', 'pBzrd4-qBY0', 'xFGuXOIKtWU', '3mugGf0Ruus', 'jufzkBBSgp4', 'dVFzCzN4hds', 'JZOqx8v8G2w', 'qorpYPDm13w', 'z6_eOBBF04w', 'TXXsk676nK4', 'i-uFuyc7UOE', 'mIoaF-jD4dE', '1UF1xmi7rM0', 'w52wB-2hwwc', '5WWtqIWJqqM', 'mzJevEfsIc4', '-7vetwzLgKs', '_MgeSTzbbLI', 'fHcSuHNRWk0', 'dVZ4KIZQFJo', 'JwJyK9x3UtA', 'zZ6bHW-7Kx0', 'IzMhxk6zh70', '9HYjyx5hiEo', '7MQOFPJVWOw', 'txoRwNYMnKs', 'Wq0lv_cL5RM', '8sdA5F93xAg', 'pUmzqF4_UZU', 'E43513OZYU4', 'kc0JTS9Mshs', 'NhT8qTSEAMw', 'WQJtSC7AIXM', '5wbJqWCdMxY', 'yNpun9-tspc', 'jI9yYZI2WZ8', 'a3gAwzmFkDo', 'L2Lhw4ztA5s', 'WAr3DSa-xlA', 'sGtgoelN0tA', 'ITcUyzY5ddY', 'Bjpb9AN9IFA', 'Nl7ShTZKGMg', 'eO6wph7HfhI', 'HFLX2Whnu2s', 'rI5iZgXtV3w', 'IVI5L18mmzQ', 'QzQhtsTdHhM', '29ttX8HNNXc', 'e2mDYEsQEPw', 'bg2yAlaT9TQ', 'VYOV4gzaRA8', 'Z5gHdqe4K9o', 'BxsT9wCiLws', 'KxrAnZCIzMU', 'Ej-v1zIvvDg', 'gkcXeJImoxM', '-EAUV_Oa8FM', 'TNp8FTCA-LQ', 'S-ks3JHQP84', 'ZO1b2idLuIE', '0nf080m9uEw', 'ePC_iyR6nBo', 'EcfAfjXklSA', 'xceKOUqNXAU', 'baWA78Rt21U', 'Gnz7KlYHQz0', 'OY5SiJAw6fk', 'Hd2BphcqEpI', 'LphR3ITSHAg', 'wmzm81vp09M', 'B76i7EaKtWA', 'SxUkMG2Io4w', '584Qvyv6WuA', 'jWB0JU0uF8M', 'W7OmksuiIpU', 'MdaP0HnzGuo', 'Z_WKV6oTnyc', 'p01M6SbjXas', 'MlqStGTO7Og', '9oFoAN0-8P8', 'a4RxLqT384c', '4UhCFi9G-ig', 'm9MYp9UEgOQ', 'wqMF9V_mDVk', 'xnpyTNK4U9U', 'sm3y7UoGf1k', 'qOnBY_uVrO4', 'qkxk__t5lkU', 'RDBDQA6En60', 'mY6U8VN5dIo', '8SrHac0ykxk', '8LoaGxCFsGQ', 'pjFDSoq2zOo', 'kQMsLTlkEqM', '0gH9qNaHHJE', 'y55_KgFts2Q', '6cTfl2Za7rU', 'NIG73862QzY', 'b1t5W9LLih8', 'qnZhf1crV9U', 'ITZpJY6K4wk', '_YprkiR8wBA', 'rBA6jcA_1Y4', 'Wf6ct1PTqBg', '4F1RV54nYro', 'HXA9zmm6eFQ', 'reoK3Rqt_Y0', 'E_ogC3r4N0Y', 'WqCVLEnggFY', 'levdzjNSPN4', 'gSsIUzRLHyU', 'Dl0HroHEVUc', '7WDfTG0F1jA', '1UQ5dJ1uCT4', 'MnAeyYEy2Ek', 'TbJkuPRKOr8', 'Ge2q4Q6yV0Y', 'AD5-xyS5zKs', 'kVMdXPHmnPQ', 'G7wWnmvHMj8', '9yYf3g9EaEU', 'JcDcCh0jJq0', 'r4diT2073mM', 'lV3pF1BWec4', 'k0JZBqnTUoQ', 'O-j2dhQdk44', '2SNwsfc6RVo', '7iN97oL9bqE', 'SxMW1pmXi70', 'S4yPS2NZkrU', '3DpOAsfQpXg', 'Uszz5oGYAbE', 'yx-hCyc-CpE', 'C9dTRS0cOAc', 'FcUtjX0txDA', 'B4OnUQEfDhA', 'GbPUgTN-paY', 'AQ2IC6KoCio', 'FzSTJq_fpv0', 'OUHXHhlymWw', '0hoetbRTmr8', 'GJnBufhoBc8', 'iJv7GN-5Kyc', 'mLZQUvV6N1w', '1o2SiI_Pgg4', 'jHJtgcLGT5Q', 'Dt8ZSKzSi1s', '5kONlEBLelM', 'b5FcdLujmNI', 'qzkNNSn7d1A', 'tbSxgiXOxHQ', 'TNrdwGvhAEw', 't2KeMDls3qk', '6n03S6XEZAM', 'hnMZm-Dgrk8', 'XLYd_QGQS1U', 'jriyXjT1ofE', '5DTOjpibz58', 'EVnUiEV8hO8', 'Y4ssar3pA8M', 'Z2N5b3uxwpc', 'Ee6GN66rm8A', 'O0wmlMQmdnU', 'ydN2-62s85o', 'kCGNRTnmJB0', '8IZNn3OABWk', 'AIuiN-Gy81E', 'd2TF6YdnTrU', 'DY6xVKmN41U', 'NRxJ3hHt4Ek', '9TVB8s6zjdI', 'o_d3hR4XlBU', '29YZRG35oPE', 'bP66ZPXIFP4', 'C0cAQ2ru9Fg', 'HUW2WIBVUJk', '-2jtMsQHTW4', 'IxeNQ6_gdlU', 'hHKilPAmDEU', '8OET5d5zhas', 'BBsPsVXBlPQ', 'mNXRbs2hA5o', 'gp-J9du6PhI', 'PqnM4WcU71g', 'mGPALmi7qFo', 'HyuAlk-Dofc', 'XPaXZ5_oKvQ', 'hQVNtXIy3B4', 'kjJva6Gf0VQ', 'dTXT7qORWJo', 'hTFcQYI2miY', 'wjRy7TDl8-g', 'UHwssMmjdRo', 'amq2vsrqLvk', 'ZB_deOu3yPw', '8puGqdJzJwk', '9id6rG_EcDo', '0ulZcOCA1kQ', 'SUvgQB3-JII', '1mLUoUkOEhw', 'YwrO8KmdEoE', '82wTWZpS6KA', 'VYi9TKDCY4w', 'PXsn8WkEonc', 'Hc1Bdai4GA0', 'VhENu8yLgVo', '8nuf1RFlJ5o', '4SeISmgBnic', 'iP1t7fNP-So', 'sL2EGDyh4cs', 'Ox9iSG8S6Zo', 'Em8RWkYC1bs', '1ppKfF7dCnU', 'SMqewkANMEg', '3d7DB4SXiO4', 'z5COibJdyXE', 'ob_lfEf1W2U', 'piTVD5hg9gg', '5iaGHMbBag0', 'k2U6TBdVpYg', 'GKcsRvT5-QE', 'sDQroJIVBdw', '4Z5nsbonOKo', 'gi24Xl2PJIc', 'jzDV02flhzs', 'a-d1SbczDNY', 'gQ-2jRDxPHw', 'sLm9zbGoli4', 'AtfiRS8TWIw', 'Drq9bG2Is3M', 'Fe_xe-rb2tM', 'l6VoUD_E-r0', 'ezKt8ftUykg', 'HloDI_4I4XE', 'gjcHNjq4rQU', 'B5XsWpmM3mQ', 'Q7e5SS3lw1s', 'pbekl2XlzLo', 'Dqg9-cZqVw0', 'u8KcctCDXeg', '_WNHHxl3LbQ', 'dKVmBTMZ-Eo', 'T4_a2Qy9OWs', 'l52e3qmwXFU', 'KKs20kxrva8', '2cO3SSN1-qc', 'hnZWslNgyVI', 'sE37HS0YkSU', 'hWmhjRTeH8E', 'ukqw6uw6Khw', 'Ih9g3L6EIXI', 'lUPbjlHDJN8', 'S_Ca158LEKY', 'kM13UVMKsEs', 'MFzaB2jknwk', 'CLterTjNDQM', 'BN1Gdi8kU1M', 'JzI7zLqQovo', '4sVuul5S51c', 'vAFvvFxgpeo', 'vDr74_wV3qo', 'psDt60SP_UI', 'IJm9rjIlwew', 'NiC4S0D4x9w', '3FJNJl8A4dA', '-KObTYIAlGI', 'GTPBQs6K1Ic', 'JVbnT8K9-cw', 'lbL9jhRW4gI', 'x1Ev_MOGavU', 'OvXwSbqC5-8', 'f1OgBKGnNuE', '7jlgwe33El8', '2jbRP7Ms1Gg', 'ui8HQg7dKWo', 'jysfiYxpxag', 'dBTYcTVYaaM', 'K_uL3N4UAYE', 'qxc3YRa52xE', 'RszeyCV_k9E', 'fPLvqajYUVA', 'Dl049l8_LVg', '_GqIdUaZ9jw', 'nw1AI9RjiWQ', 'GTKiFIIAcYY', '0lbalaygYKM', 'hAmD2KYhyEs', 'N7oJFUvJJEE', 'eFXq9vGqrVo', 'vDsWU1qV_0k', 'ALNsRWH4p2o', 'hp56eVrW9H0', '4KlBDJZfPiM', 'lyhlsmOCphE', '84_MXkDpT9c', 'DxShbwAMywk', 'l--RDZ2M02c', 'RLHD31lL30k', 'etFme4RtqHU', 'aadp6xDm6NI', '0GXZj7ZpQoM', 'PDdDCuhQAus', 'ccdXOAkY6K8', 'slNxj010iTs', 'b_PRAZVOPKU', 'lsLGdCoOIWg', 'kIV5E8NVtMI', 'HMHS5hZSttY', 'Sg_CpXW_jyQ', 'ySqUSxiIWjU', '3gnarKigGUk', 'DNCggFRtFjU', '3NzTtNd-3ps', '0MHBDarq27Y', 'EufoN9dLzcQ', 'BejhVLFW4Jc', 'hbMRv19SkXY', 'uonZ359GS9k', 'P1iHAm3pppM', 'lnIxGL_fP9E', 'qNVLV25-fpA', '56bSWR-VKEc', 'GmptOlRBWAQ', 'nVFNYlu3wUY', 'UqjGBhdBQB4', 'N0cCh-vXcLU', 'agGfgPjHPqY', 'wJ72yG5kkzQ', '_WvIWADgdQk', 'NpjdeX6Krgg', 'hUsI8fGBEJw', 'h9qmpVEFmX4', 'pne2gfr-kA8', 'iEFZMeuPc_8', '6qTOXbOU_4s', '6f2jANwqhJE', '4j9gWS1ZrpQ', 'YLu_MsWnGyM', '-1tZi-W25Dk', 'Jx7rVtJNy1o', '123htCaRF6g', 'q-AqKRwC_34', '1QD98TOWw-U', 'm5sminFcRKQ', '8W4bLxQAQgQ', 'hZfgUUKqAXk', 'ehj7EWO2uLE', 'fAI38QNDdOg', '7037po5Dl48', 'yb2zeW-mtYA', 'yXB82Ib3Evs', '8Klh4H_O1fg', '6iNoHASA8Nw', 'pHDBbGNQE0I', 'xxKC16YniBg', 'F4v-eNmWECw', '9afTMBAJZgk', 'eRUN1Z6RbEw', 'JYPGKHn7ErA', 'mXKIy9AMios', '-UbhrfPaZwI', 'bwJEF0HFTdg', 'tn1rN0tu1Ro', 'r0NrtWCux8g', 'kVgdUeLJUak', 'hWvnl95xAHI', '9QklWP-TptE', 'QCR0wyMbLes', 'owsBtnehXKU', 'FsNEasL2zp0', 'zQvXD5QlgQI', '6jezePkXuWA', 'rnSj3z1iw5U', '1OyMTBHgiNI', 'Y1JGY7ooEgQ', 'psM7zXvdg2s', 'h7CdnR8KIQk', 'X2uUXSEJHbE', 'Tz1VkMxRT_s', 'PEK6sjS9Ehs', 'wQZ-VeyOX5Y', 'ybp1BTQG05w', 'GU6eSTUxgdA', 'CpYKlg16D58', 'SIE1_sGzsN8', 'hHi4vAiA5lo', 'xTVXY_nn6ug', 'oXO7y0JaAzk', 'ZWkcix3Sz-E', 'oQlulThTa7A', 'B18vfSdAdLs', 'IxAmUVYH5RE', 'ZgbahaAG1HQ', 'fZTXvGo-ZdY', 'cayheNU39dw', 'rOmXHgbgDQI', '2dR1pmhgz2k', '6E5lfTicn6Y', 'CPnJHdCJ24I', 'Wu_Sb_jkr0s', 'Rp5QRKqrUAo', 'ugaGvXNdmhw', 'NwKWXDyRvMY', 'H2H_2LRHAUo', 'qD7g6Ot9bXo', '4Fof9JgjtSk', '_O6F0I0axlY', '_B4SKamoRG0', 's_jqz4uYNCs', 'ECBZlPqN_Z0', 'fmZK3vE_el4', 'Kx34V9RE59s', 'sdWeEhvqLBc', 'ctVu3iaQRr8', '5QlLzx_R3Fk', 'j-CZgSNYeRk', 'vEUTBblkFoQ', 'jhAyeFZPJi0', '_WUXlCbWdfQ', 'ujPsAcoSzHk', 'T7d23jBGToo', 'o2bc38WwBvQ', 'oGeoVigaw08', '4Rj2f_18bo4', 'Z_VGwnxcQtY', '3-Rb7l5FLZU', 'jb91cFnlVkg', 'i-uD2AZbuZs', 'i4Afqq2_O7k', 'p-r_TXqXGZQ', 'V9JsAX2MIyg', 'DFWtYetoP_I', 'RhkFxvAvvd0', 'fMx7-5EDErQ', 'nm2is67L_xY', 'MpIMyuk-Il8', '6kxg7jlaNo8', 'Ck3BgVGwHpo', 'eCbDfH8Oni4', 'Gr0iLB59BxU', '_7x-RvBAA1M', 'MLNDxyyL-AI', 'Mj4GIUSl7-c', '1M3tIKXCkUs', 'SoUH5V67qLg', 'g6oCHJtLOOo', '_GPtQbeWW5Q', 'pwpI3gL8SYw', 'm1cgoxoTulk', 'ohRZoFcd_gA', 'l1ydrXfFE0k', 'zM9jfgh3b2g', 'GzOrIbvYudI', 'FTnX0hFew6Q', 'uLvJ6YqBZIw', 'KWvKLvYreC4', 'ADHzilNFA3A', 'ijEWktp9OKk', 'fWjPDo0QO_0', 'QQGtk0917kE', 'FzpjHINVsIs', 'X34-iSrxiJc', 'j_gu1q9L1s8', 'LF3PZ6ewipg', 'faLRzPVRTvY', '0YQjsDJ0jww', 'S7iCKYpuj8s', 'S31jGrP2eM8', 'QZGrvJujDUo', 'VdTW5-ssfoE', 'Jz2gCdbHAMk', 'nBlY20m9dZw', 'MDyrOuPMJVw', 'AlPKbO3jUXg', 'Bgj4Fw-6kWA', '0ewPOycZLR4', 'Dj6PgunrQFA', 'eFXx0hu5dfo', 'gCawWTeGVeI', '8C8_kSDO-Gg', 'zfXXhjr5tyA', 'J5uY3JM-SLc', 'Vb4opm2gd0U', '5PD3S-LZkk4', 'JfVv8K4Z-Qg', 'w0_-DY1vCvc', 'ue4hFtuWpnw', 'wKcLHQJs4a4', 'BjCjePdowFc', 'vkOPJHnfibs', 'YV6UUvp35Mc', 'Bb3gcaNzdEM', 'vjLeTTtQo3M', 'SEIcy5vNf0U', '5hNZtseYru4', 'jucLS44iOkE', 'DxEdsyuUO6c', '3ZnE8kaTfsM', 'WRYPzhBNqoc', 'q92gk0izYVQ', '8eKzxvu84D0', 'BM6ox4DqL7M', 'h_STTlrip_k', 'nK4_QCeTRvA', 'xwvp1sJdVo4', 'pYIWyPVv9mY', 'DLE5W8wEpTQ', 'bRYs8evnt2w', 'uV4L3AhLcAA', 'Xbe7WuOT4Hg', 'lC4e8Uh_C-o', 'cRykZDnJbW4', 'uyi2RT3Kak4', 'Jpob_WQ3CQQ', 'NYkMFnDjr78', 'QP0ddb4b8zY', 'KjlkLYnxueU', 'yxu5ZfiZHSw', 'yRzpanrzrK4', 'ihQE_G_-PH8', 'TuSrNAtW8TA', '3sfGC7BcTSM', 'jPOoSz4Ab1A', '0oGLGq1I7E4', 'G7szSKp6DEw', 'F0RbvnNWgk4', 'oE4rCB9snAs', 'CbQ6fS8KumE', '5VoR9JNSuNw', '1r68LKWXx4M', 'M4nkwDAvRgc', '0CabVA4k1ns', 'Yz8-j2hWYbo', '43wx5y6OYTI', 'rj45JqmE6vU', 'cue_8Z7Lw9M', '-pWALFCg3Og', 'cKn4i2dvya0', 'E20Ljm5D7yU', 'CyXOX2_Hhf0', 'eyyho2-ErL8', 'iBpU9idmeVM', 'PV5a-blaM_M', 'i5-hbIrPaKs', '_oxx-cXDZbg', '64KFrJjunEY', '7Qf9cY4yk3g', 'ZJ9K2o4Rck8', 'yQT_TmfUzb8', 'U0DYJIRD-6U', 'KSgsat04lLk', 's-tYE79uyCk', 'MbDBr6j6sIQ', 'gLtC3a-sIkU', 'tL_kwTUG2Ag', 'MvoNVnjH0Xc', 'QdP28hMV3MI', 'kqtngPESsIU', '51qrUENkjMI', 'IglBJ62Sv3Q', 'joTn5hgyI0s', 'hbSY37dr45Y', 'zNVyU1X8mrA', 'i706ZlA3eSM', 'BkE9zNlNEsg', 'OLxbAW9Cid0', 'Q0px4Qwyrk0', '9eUoIuGJepg', 'G6sPG0n4R1o', 'aR6_cG7D5c8', 'lhGSR1iSsCY', '29hk00wFEoo', '_O2pKqX7Tzw', 'fnw14-fLoeY', 'JYdu6VgzRI0', '_YwrI5SlS8Q', 'Bo-dgSkNC-M', 'Yxigd9dlsd8', 'fq4RoLsa5gw', '_Fvee3MaAJg', '8t932519vyE', 'oERM7trctT8', 'eldpYwG3tEg', 'a7cUcKz-44s', 'aTqhMdQjLkI', 'V9YfnLGoJL8', 'ozhVcXVv9QQ', 'MTCkfcPlGOA', 'yUAgJ5GcnXQ', 'SrbmOCiHqRk', 'vp_mLVO35w8', 'QhohWWvpB7M', 'H6IoNSNnl0M', 'k_zBkqBTFtE', '1rXC2JJyHiw', '96Ol2RQNPSw', 'FGbvnLBUjKw', 'fAvaCJWf9TI', 'nDya4ooODQ8', 'zJg7j5ge9EM', '4iHiPrjeVcI', 'NLGoWEdZy2c', 'jSP-LV1ue10', 'J101G5AnGOg', 'NYi-7iaqmHk', 'OWl5PxRmw1w', 'tRuCbZf71h4', 'fi897xwV5Gk', 'FKO51klKNQw', 'cFB_p7Xif9M', 'DiDUSKTg3JU', 'iQhk_YZ27YA', 'OM3yCSjI4P4', 'wiXXrtye0NQ', 'rrhZoeNQTa0', 'tgnNgw1upyw', 'lVNc1CUTX_s', 'QPQG1hXKrgU', 'K9IqGyy9UnE', 'zbvO0S46W-0', 'quFRqt80l28', 'wIYLRDZEMzo', '5GvJqkDOgBI', 'Z7otAwjufF4', 'P-T3HKA0FRA', 'jDVbT2Hc-5Q', 'I-qoTGhdnJ4', 'gYcWA1v6Njs', 'i8zQtMUmRTM', 'UHOIaYOxKlI', '8rFsZvVb_xo', 'f5bRHHk0RvY', 'sro5NH4ELV0', '1v4h-i2N5KM', 'LgXHIfGsEnw', 'PlaQGL3VVBc', '1T-lBDKXTV8', 'n2TxR3bDrVk', 'FBRSiSjDOSU', 'thXstqQcdQ4', 'zl6BuEwLyLE', '4JBuW-Y0eQg', '-gqs2mTVSPQ', 'U8LCE8YPfic', 'LzrYwbFxkIc', 'T_OofJ8RmgU', 'hTBFFIgVbq4', '5kwa2T9qDrA', 'CPcNNzePZh4', 'qhCnB5QsEPM', 'Ec-ZTHgUF5A', '-toUdF5wWq4', 'q1PBDoRgiMQ', '-d8sNML3WT8', 'icJ9WNDWTSo', 'hiTQbEXWo7g', 'bSQHs0eC9Zw', 'TJ64ItDUDF0', 'sjKqFTBjpw8', 'DWiZGlNxoOA', 'YCzqSUR3l30', 'YyLcD7_vt0Q', 'f5XBlzi9-mI', 'U6Hi4vbekME', 'ZUQhxv7Anwo', 'nPE0GkSESU4', 'cNwnDW_9-3c', '1UdUcBaXvy8', 'vq2uxgWHhj0', 'y7Hu-8NhuJQ', 'wJxdEqQjr3M', 'R0BX3NzxjsY', 'zk1JKWAUOGU', 'UuU1ZrsNIO4', 'GK_X4jiR7WM', 'sbgWwg2Ykew', 'rMDRIGWolQA', 'tObbUX1gulo', 'SH73ocAu0DM', 'QqG-2_ceNX8', 'U0_6GdH8jWU', '8g17i73Ek_I', 'BB-UaywSp8Q', 'w9DNCBWV6qE', 'SJQKPXYRTBk', 'b3pXzVF-pyw', 'TM4ZDL60_F8', 'cG51q6CRRyw', 'cHJ9btr1QJI', 'SZyBcsGvBYM', 'ZSy8Ic_kSlo', 'bOXLFbofEZ0', 't91lX1pIXpQ', 'brWi7egHV8w', 'Rx70OYVqdEo', 'WhhovQ7HW4k', 'FPxzNEL8nzk', 'YVA2cd7T_to', 'eM-YjNHmM84', 'na_dBj-suvE', '7Vl9oU5UnTE', '8W1c4XnO4qk', '7PPctNhe99E', '9UiKdm2Yqd0', '-cRGIXzrzxA', 'EoztrLQkgew', 'nuiA6-36Mvk', 'Ygez4GCkDZU', 's8PLSGxWVbA', '0uzg-5tpaXI', 'BORVxbsdkCM', 'i8XG9HaS6Ek', 'Uv08g7LVjd0', 'R1XqbRCfefA', 'mU1IdB7rv70', 'OJdwQpR-FvY', 'R6DSMIkdfdI', 'xQWBQTmnMro', 'YIQfjcF39Ms', 'M7u7pRUXokk', 'tB46WSVuWnY', 'u4iqN_9Xt34', '_ahir4HVOHM', 'Y-58152x6JY', 'QXCfGFzYF6c', 'tWk0lDHQAJ4', 'AM2K20qtDZ8', 'zclclhg2TEI', 't_KgTaAsHLs', 'v02S6MEPFxA', 'lP_Erg2doCA', 'znxF94TnoT4', '6JMjUGp5kUU', 'iVBcVbx_HQA', 'JxSnVmJ6msM', 'elk3cObSTEs', 'sR8ADZOcPho', 'm8rDhS8y46g', 'nrB6AJOhpeY', 'M9twYdhUrFQ', '95_-ThLpbJ4', 

In [45]:
df_dim_vids = df_dim_vids.drop(columns = ['privacy_status', 'license'])

In [46]:
df_dim_vids['audio_language'].replace({'en-US' : 'English (United States)',
                                       'en' : 'English',
                                       'zh' : 'Chinese',
                                       'ja' : 'Japanese',
                                       'ar' : 'Arabic'}, inplace = True)

### 3.6 Data Cleaning: Boolean Mapping
Converting boolean `True/False` values into descriptive string categories for easier dashboarding.

In [47]:
labels = {'has_captions' : ['has caption', 'has no caption'],
          'is_hd' : ['HD', 'not HD' ],
          'licensed_content' : ['licensed', 'unlicensed'],
          'made_for_kids' : ['for kids', 'not for kids'],
          'embeddable' : ['embeddable', 'not embeddable'],
          'public_stats_viewable' : ['stats visible', 'stats hidden']}

for col in labels.keys() :
    df_dim_vids[col].replace({True : labels[col][0],
                              False : labels[col][1]},
                              inplace = True)

In [48]:
for col in df_dim_vids.columns :
    if df_dim_vids[col].dtype == 'object':
        name = f'{col}_uniques'
        liste = df_dim_vids[col].unique().tolist()
        print(f"{name} : {liste}\n")

video_id_uniques : ['WruHZnB_srw', 'BDqhOhr-orw', 'r3p0R9dlKww', 'Gv8mItBLZ5Y', 'dKoIepQtPO8', 'dp5QFSjloNM', '1Qp1yaSpfx8', 'TM47c__WOfQ', 'bG6bXMhy0Ps', 'x3wVNJlem7U', 'rWSL0v-rmak', 'OCGQIAk8zIM', 'PJqh69mNTtM', '_rcRea7DG10', 'g4oIYbI9tog', 'sA_U4DhYmbc', 'QQvvO8Mqk1w', 'yqBwFlECOXc', 'QG6cEqow99Y', 'KmE6OPhpLjw', 'GtjkUge5aew', 'CngqU51dsJU', 's80mBDNJ5lo', 'oslN3LtaBqI', 'SIjMGjKA9Rs', 'bzDonR6Pfo4', 'I6LPhS7yH-c', 'Pf8eNoGqut0', '9JLKfP5uJ9E', 'rCjtlBmKkMU', 'shyDrSrHcwo', 'ma5IsOYGxrs', 'pOi_AQ9F_Mo', '2-s8P58EwTY', 'ZyGH4eUXAX4', 'nD0bNdRu0w8', 'KH6O-MuUdB8', 'GG7j5PqX4UY', 'yxF_RnU400k', 'dfN3BQt6i98', 'ZCs_Z86qvYU', 'jCkvBQWhrNA', 'ENRrTJdlyg8', 'lRUS-7P0a4k', 'uGkwc-JWdYw', 'ydqkCytz9GI', 'BsEfPvIrVCc', 'RljBVCnt9AQ', '5MIn6v9h0oQ', 'Qytqug0QgKg', '1d_KSbE2LX8', 'aMtaVPjiOqw', 'NwTg6HjkEgQ', 'C3VjFb1_ct4', 'DUgesPqAztc', 'jvdo-c0Pa1M', 'vSYgZG9UNN4', '1YDQiiBKgTQ', '9djOjC1Uszc', 'FfqVuyF8wnY', 'ULPQZsj0J2Y', 'hohnMVXn91E', 'HjSQ10zDB0k', 'T_RbZxmafrE', 'bvqzzusB-_M', '6_aKBUfY2Yc', 'LyeOo_muleM', '9byGejq8Uko', 'I6q1AUJWAUk', 'WgxrMaHvs-Q', 'JBBZyYBvtxs', 'iCYg96L6GWU', '715dmYhlF2M', 'GbliZCntNXU', 'HF-pV_7XRyE', '0MOwdS1tU7I', 'qVJZMZB4NTY', 'liJHbQN-N4A', 'bxVvA8SfJpc', 'sKQbArT36AU', 'NYcv1ZFZTDI', 'k9e6ejg3UIk', 'f7usxflVNcQ', 'Mnv6y3MVVKc', 'dHjvgtu0PXw', 'jDoXsHpexZs', 'mceHQqvOIJY', 'hqAgQadwDpc', 'ebx7JyeTxYc', 'a557pgwd6MU', 'KNWDmYhyA_I', 'BpfnV05fXrc', 'vV4Rux4LRds', 'lOha9RQQtAo', 'Ft8TGsaVs7s', '3Vld5h98O90', 'T9AQJj2Pquo', 'Kcq0tjmvGOs', 'J96c34NHhls', 'FhqUKeXutuc', 'RfKlcttNBG0', '47z7MGHdyQw', '9LRuaQ4594c', 'bTXr5-jTcbg', 'l7SsCzP0als', 'YvtPHoQE4os', 'aOMyRHP2crU', 'zkH6BifgaE4', 'Y3K8Rc8FR2M', '66iCIfoCIVA', 'qEMtQjcjIIc', '_CTu2FMk8l4', 'Zp3Ajt5U6qA', '14mEq7iUDjc', 'o5opXRMhcyg', 'kSUjDfNAiuU', 'jUH94mP3Yas', 'eo06Z1Vea9c', 'Af72fKffNs0', 'zTa4_-oSMGQ', 'kddthyR48PM', '5Y_5MozNiZk', '7-MII1LYkpo', 'tyoTyquAUis', 'ZReJpDphqQQ', 'IIeOvm_Cv6M', 'cEquo_eCMWI', 'J5fbNMGggDE', 'l-KpNxmDOio', 'ORzslauiUik', 'O5pxmhXbGME', 'c6lryBSrSAQ', 'bkTrtv5nVmc', '37uoYrCxsDs', 'RxcqWG2ah9k', '3tWA_hgNv1w', 'I7OhjHyAUbs', 'n3YcToYHCB4', 'jGGQ-UxVjCU', 'ncBXvkIWihM', 'H_dLm5u0mQw', '4Kz0CdFVGCI', 'pQAmvlgt9CE', 'yKeYKNl4RSc', '6Gyghgj7RhI', 'uxe4OrNTU2c', '0mdzlfQQSl8', 'lJYlTAXn4t0', 'TXdVyunArDk', 'f-bsab93UZ0', '6yqLaG14qB0', 'E4HECt5orOA', '5t_cfBAcTDc', 'GQPg_JYcgt4', 'ZMFlXabFXBU', '5wB_wgOsR2g', '6RgJP1wIuls', '-_RBZfd4ZBg', 'Gu8IXdzoulQ', 'X05BsYqZSdg', 'So46F7v2jgk', 'Qt3KppJNDtE', 'Dw5OETIQH0g', 'VtltG-fQBzw', 'mo95GRqzEKw', 'urlKiE7Vpxk', '1_YDTGnir4g', 'Tqo2hMcLmt0', 'W8AzYWnrSmQ', 'HLngxE6C4v8', 'R_MtUHR1Pxo', 'L-1onPXTTyE', 'BjAjviFHAMo', 'qCZK46Potp0', 'iF-EPsbNvqo', 'VWH1AoZTBxc', 'ok_2fqku9ik', 'A0W4igjZKpI', 'AbVuU_fiPiw', 'nLzQaj4__7Y', '3xGA-QzW7ZE', '3RNiQ4EaTJM', 'U9lidC1C8xg', 'uxyd6tAI-ZU', 'jDjZaSdwJ5E', 'PCxkI49hrwo', 'c89_HXgWTQE', '8adECUCmP90', 'F38aEkyzfas', 'flfGrcsjVus', 'SbSK7EBlB10', 'QF6fDItt-Jw', 'v-8R55oyYfs', 'xC-J9GEzkW8', 'i7PqWY57-po', 'oYEGRC76mV4', '_8vNujOWXR8', 'z1Wyro2vXgU', 'y9SDUt5wvak', 'bC6S9ZuR17Y', 'Ss5H62LDiMg', 'm-umNBbDK1s', 'wgsh7VTJALY', 's-Ac6CTmoMQ', 'qji1mbzo4wU', 'swgm5dDAcMU', 'Asc_TrJllyo', 'xUzIqdEPC-k', 'dGRLAYW1QHQ', 'pwFUrE2YWjo', 'S6i2uHkj8LM', 'P1Xxz9j2Cgo', 'GDuq-A0djqU', 'mm6UJ6HjwXg', 'GwugYT9zB_4', 'XzVqbHxw9ks', 'yptrdzTTDSk', 'vW7qhbuDgS8', '5Cv9qU-TfqI', 's4679CUuMqo', 'guCkWXZlQfI', '8dcZA3IfDdg', '8AKn-zJMIwY', 'NZXfXmRYbQY', 'ufnAA6KG4_k', 'vNizX0HIqRA', '6V46scOHnA4', 'yFX_rERVjzc', 'ZyRmGNCZd5A', 'vFigtFoMObg', 'maTntMnYAMA', 'sD55v2WYUAY', 'z9Pl4GIKQdM', '1zuSeOznrDM', 'Qq0qb4zRzcI', 'FaV6n0tGeoQ', 'wfXV66nscC4', '_1oVKuG3BpI', 'rofyxAwDQAU', '5RgSuHeM5wc', '8mPUBuTtz94', 'Uwe4weUl7RA', 'b9orWxlPNAo', 'z0M8QchQGXI', 'yK3_RriFPuc', 'ZxRd8rI9o20', 'elrUpoc78SU', 'uEISc57caL8', 'jij6YLMEhoY', 'd0s_s5GZWi8', '8GW-TdHbLBU', 'n1P0U3uV7ko', 'zOd01sLlDj4', 'YmdoYptHGyk', '-0GPWaMBiy0', 'DLAZX4HOcUs', 'rpMnfBcWdO8', 'nbBNt1UhF6Q', 'Jb6cWp76Np8', '7q9KYJNu-R8', 'iJKEg4y-dRM', 'KMUZAUF7-ok', 'k6SY4Swn0Sw', '9wlEM7VdRjE', '8MygYVp9AMI', '8_AwER_bLEg', 'rskbKTbBD-E', 'LBqeiB7jx-I', 'suyfDsM8YOY', '9qiJLPkVY7Y', 'cHS_6uISd2I', 'vy1JPpTlOdo', 'YYxUhhwWbOk', 'nqn9Bzoa04E', 'oTV2a5fjN0c', 'XPfTRI4sazM', 'pk0Zm_xpk3c', 'OlFClfAw9hk', 'xiY3tnyTzpM', 'Z9xCK-AhpAs', 'Y6sEDYZMYec', 'lfulsZ3flGI', 'Lr1gWNnIPLo', 'nDzIevSAczY', 'h5CM_5VA2PI', 'sN1AVSZyFbY', 'LL7Kt6gXuXY', 'wuTTamqrHWE', 'vOMnrcYG8O4', 'popSWtKu33Q', 'jNxiE4zlgLw', 'a0nrXBJ0-0k', '9V0Uvxp_oXk', 'QCCxc_uQJ40', 'wQMCdDTkIks', '_qfxaeL76tM', 'nBjgngg6_bE', 'hG2PgyuBiYs', 'a173gcrUl4Y', 'YDSwb4DqD90', 'B-lF-Bev3Vg', '2e61nFzLKYo', 'O1-WQhtcmh8', 'hP5lJ3nlyJw', '_6WnF4Rbhjw', 'nDGD9hmWtiA', 'ruYCVuq0aCY', 'HHQHQkz4Mx4', 'G17MaGbUieo', 'tN-6pT7nsx0', 'Q-8nM3ydZw4', '62GkaZdg6Hw', 'sPZebkT92Qk', 'Btq51euV1HM', '_K5LhLUzYuc', 'bXp3ZdPzIFQ', 'o05t0yHfsqU', 'bBEB_HB9bsQ', 'X-FKuKtO8n0', 'KsetTg2Y2oo', 'NIDLendPlec', 'brJ2In0kN50', '16Nrq1EXKdI', 'Me-G1XklA0s', '9DaEmvKWsEA', 'CSSg-jYH4L4', 'yWXnfY_De8M', 'wb5lvJ1KfrU', 'wBuOv5Qq_Qk', 'ZmzqQ-aPv4k', 'NrRub6v4vEk', 'Mr8FCpOm7Lc', '8zaDExHamSI', 'nT0aZ3-ftdY', 'IrRmgAyQBnM', 'BbkvQSwVExs', 'veNBSwR_9mM', 'YnmpMJH5cr8', 'f4CuHjhvNE8', 'u1w60-USuSM', '4dwe5wewSmU', 'snc4-aFo8Ys', 'kMK78kboyp8', 'sf4SmfywpoQ', 'iigq57akfaQ', 'Fw54dW2Rlmc', 'n66lHAF-jXw', 'I9cOuxq8f60', 'UA7Ho0rcABo', 'XaDdUIg-mCk', 'v-82Lg1rTMs', 'h7HfKejfqcE', 'L9W-Wz5DUuk', 'o2Ht3c0Sdyk', '6ukcVg5hiks', '3AacqRQ002w', 'P7q73-d6Yk4', 'jXZaBv3po-4', 'J5ICLh_TkWM', 'Yc827HubVjY', 'iwdN94CL8Y0', 'i_HOGsV4JIo', '57qSDw9G2lI', 'h9nVYFLr-JM', 'Qq-Guy0qOPg', 'LoCYgZeHkWc', 'ZDKRT5JQewg', '5iBPuchwb4E', 'U-X8w2q6YqI', '_XvnvCeiozo', 'iKnZ51uBs30', 'ZPRgsJF70Lw', 'rBIEmqb9vmw', 'cBNruRw2zA4', 'aUjTmYa0xKQ', 'RItnli0kAX4', '68sV8Z05M4c', 'vdLZMgXHvYQ', 'hXYa4-yXp4s', 'LQlGuahgCHk', 'PvYI-zHwI4k', '9Tjwi93QtvA', '5Vn6OxMX0o8', 'YXeeKOYn6sM', 'pP-TQwDOGko', 'SkuJIbazkkM', 'ultPMuBnS9k', 'ioAmrgPrMYY', 'pHwQj4N_vF8', 'HCsPPQ2V-yM', 'l6gd7yec6F0', 'L7D9U3d5ZSI', 'Kt7XKGhtT7Q', '5NOumvDXw5w', '3fT0VYV14ag', '_m6ZYbqXbYw', 'BwZT5ePI7ec', 'x6k5XrNwwyM', 'CbtbN4dyfwE', '7aIRFYzLV9M', 'bVuQfXje8KQ', 'HhsZ0s3KXAQ', 'GOPr7N6BDxA', 'KAdSNaknrUE', '9Bn6eWGoe4w', 'blMRs6Wh-G0', 'v828JFvtupI', 'B_9UjwUavGk', '8Fhzz4c-a4I', '9gED4RFMOZM', 'SNGiWla9cIE', '7n0pr3LKphA', 'jGi1F43993U', '5JRf5CrGB5I', '2RgzOYNdnLE', 'fv_dx-lz8N8', 'Ap-gNRXQ5aQ', '_bFtnBBOIVs', 'r3lJQexApnc', 'e6R1KlxIHTo', 'IlnXLTqk5pE', 'Y6doBVxZVAs', 'YTUGNBU7IaI', 'XoTZItCldn4', 'BJnBBBnFKGg', 'z9OicXWc20U', 'lfY4xXfoJ8U', 'e-ABv-PubWk', 'S4lqW3audrQ', 'zV9v0RIE-iI', '2DxWimticZ8', 'cC4Pm8NS4CA', 'q0WAOgM9Aq8', 'oSiubafYVfU', 'lvvXYdKLJTA', 'Eqj7huV2N7E', 'KFPJ-k1tSiw', 'Lq-qUf1XGR0', 'bn2DXdxlgvg', 'sBBhLjOQL5k', 'diBS0VfVcbs', 'oAGx9HqGh3s', 'Wz3IPIQ28OI', 'DCw5qO6cQec', 'pe9t6sAWFXo', 'm7BdbqoRUCw', '55dMN4IIJ0g', 'l_TbfGEPtsQ', 'E8wjQAQyUgo', 'vraoo9SVNBg', '5ls8jPE5Tc0', 'TnBL8QM8BRw', 'ovaWAcTtbxE', '6BT9odWipq8', 'TTCDLykCk5I', 'M7h12QZC1tE', 't-8TDOFqkQA', 'lkJcodTB2xc', '9vfjze1ddS0', '4iY9nZHUr58', '2qbQHWsm7Do', 'aoptVvldIQE', 'EQvJ0hUXpGQ', 'aJ6kKEnRL7U', 'iiy25Q15BkE', 'c8hq5MsROJA', '5uA73J3jhQg', 'gzoY27hzOmU', 'xnW-byAy-eI', 'BSAMHp9Dcc0', 'HB4tp1lgx6M', 'XZfYXdOUQBc', 'Bba-ojcGPK4', 'mucmpKIbZCQ', 'ER8Cz4-zFQo', '-vKvS9tGzvA', 's7WZQ2kwz8w', 'cnPb6hLwkws', 'EmjEDy40hrQ', 'VyCtgTQWe8Y', 'vni148KpCx8', 'zW_c-4N-0KU', 'LRVuZ5s-r4I', 'w81PTW2nxoo', 'NF84LtM8iho', 'zOjxqgZULOc', 'VZ4HY6fGlcs', 'MPS0PMMSRnU', 'djIGZDvXXPg', '1VEHfoHxlIs', '6pzLhWCxH_g', '6qGjA4pam7g', '_ctDIlxGGHw', '1Kld0XFi-w0', '8BRHNC1IKuw', 'YW9FTIeBszw', '8d5p0_HQ41E', 'h1k3mLhhMmA', 'yg3n0hYg-zU', 'IeXGxUyN09c', '0qjUK5XmISM', '3l2uJQbbTkE', 'LgUd-4r-Nks', 'gyamCFp-q0o', 'E7wZGH52LYc', '-7BSJ_UmH1g', 'Z3rOdV4IoFc', 'pMC2MfKc4b0', '1Lo4kg51G1s', 'iEYsdIO7u7M', 'G98EREdOCT0', 'mh9RtpZPpVo', 'MZWAmty3toQ', 'ry_yeJ2CgSk', '1hiULacZEoY', '2omZgA07NsI', 'Mn2wSBBQXe0', 'fuAo5yNgUE0', 'ddxHzoCCxOI', 'tFgC7TwuAHU', 'qci1agy-j5I', 'CHQZPmISE4A', '70B0a_DDoSw', 'SApiC0oea0c', 'HyGBemaOZnQ', 'EzZk3OkGnsM', '9jISoQGdh5E', 'JfRshktzfJM', 'YfiaVHdmUoY', '-z6s4CepwnQ', 'm5GTkSK14Us', 'UNyY8owMCeE', 'nXGNDeUyRwA', 'q5ezbsiKHWQ', 'Pe2_5vOSF6E', 'D_LbhfGNHs8', '3QJ1X22eom8', 'bzXiIO4ZzWM', 'EOcW5uwcvm8', 'muKHML94YwI', 'a2G3jyqXhfY', 'C9LJTd6pQL4', 'I2BBJjFKjkU', 'fCbRQAQGWHo', 'GBt1baOWyiM', '48JVq4g_lEg', 'YmcAz68nsDM', 'o5isWP9Vjco', '1CCShSBGVLQ', 'gGV_wfRTJwo', 'Rx6fXUht4eE', 'CB_6kPtpVg8', 'Dgk9qZxZTOw', 'dJZn5RAMaYQ', '21NYmmv8iY8', '7rEzhCwPhqc', '0ApanP65Vcc', 'Ji7OVnUCjnA', '8H1OxHuzK-s', 'g1YmEjkIplA', 'a8iZyVGc_F0', 'tw_qv0n2xUA', 'RCocaLOjhEc', 'aR2AhZhCs38', 'K6FvIiOsS1o', 'RRWDH91p0Ng', 'zL1AVDcacyI', 'pYuaSKPN0mE', 'ORrQBi5dgM0', 'BRAwxNVNAxA', 'mexnaJn-Y5s', 'HRM3W2FVGQY', 'f9eIMQ_4J2A', 'MUY6aTTLvZg', '3KfLNa1xPzQ', 'cLSDTTEa8fs', '0FWy-Q7IPco', 'PxTEt6_MnFk', 'CYo2QX6cvZo', 'xWOCxtfN4js', 'WJhqu5_HzBU', '_zxtNOUKc3E', 'ftuCHNTzJzk', '2rFX57FFYvQ', 'KqSBoFXee2M', 'jO8C8U07YEQ', 'O73aCOuJrlw', 'MEG9c-Q3sKg', 'rJiEzY-VC4E', 'h2YKBp4JUQo', 'q1TYjRtymUE', 'pBzrd4-qBY0', 'xFGuXOIKtWU', '3mugGf0Ruus', 'jufzkBBSgp4', 'dVFzCzN4hds', 'JZOqx8v8G2w', 'qorpYPDm13w', 'z6_eOBBF04w', 'TXXsk676nK4', 'i-uFuyc7UOE', 'mIoaF-jD4dE', '1UF1xmi7rM0', 'w52wB-2hwwc', '5WWtqIWJqqM', 'mzJevEfsIc4', '-7vetwzLgKs', '_MgeSTzbbLI', 'fHcSuHNRWk0', 'dVZ4KIZQFJo', 'JwJyK9x3UtA', 'zZ6bHW-7Kx0', 'IzMhxk6zh70', '9HYjyx5hiEo', '7MQOFPJVWOw', 'txoRwNYMnKs', 'Wq0lv_cL5RM', '8sdA5F93xAg', 'pUmzqF4_UZU', 'E43513OZYU4', 'kc0JTS9Mshs', 'NhT8qTSEAMw', 'WQJtSC7AIXM', '5wbJqWCdMxY', 'yNpun9-tspc', 'jI9yYZI2WZ8', 'a3gAwzmFkDo', 'L2Lhw4ztA5s', 'WAr3DSa-xlA', 'sGtgoelN0tA', 'ITcUyzY5ddY', 'Bjpb9AN9IFA', 'Nl7ShTZKGMg', 'eO6wph7HfhI', 'HFLX2Whnu2s', 'rI5iZgXtV3w', 'IVI5L18mmzQ', 'QzQhtsTdHhM', '29ttX8HNNXc', 'e2mDYEsQEPw', 'bg2yAlaT9TQ', 'VYOV4gzaRA8', 'Z5gHdqe4K9o', 'BxsT9wCiLws', 'KxrAnZCIzMU', 'Ej-v1zIvvDg', 'gkcXeJImoxM', '-EAUV_Oa8FM', 'TNp8FTCA-LQ', 'S-ks3JHQP84', 'ZO1b2idLuIE', '0nf080m9uEw', 'ePC_iyR6nBo', 'EcfAfjXklSA', 'xceKOUqNXAU', 'baWA78Rt21U', 'Gnz7KlYHQz0', 'OY5SiJAw6fk', 'Hd2BphcqEpI', 'LphR3ITSHAg', 'wmzm81vp09M', 'B76i7EaKtWA', 'SxUkMG2Io4w', '584Qvyv6WuA', 'jWB0JU0uF8M', 'W7OmksuiIpU', 'MdaP0HnzGuo', 'Z_WKV6oTnyc', 'p01M6SbjXas', 'MlqStGTO7Og', '9oFoAN0-8P8', 'a4RxLqT384c', '4UhCFi9G-ig', 'm9MYp9UEgOQ', 'wqMF9V_mDVk', 'xnpyTNK4U9U', 'sm3y7UoGf1k', 'qOnBY_uVrO4', 'qkxk__t5lkU', 'RDBDQA6En60', 'mY6U8VN5dIo', '8SrHac0ykxk', '8LoaGxCFsGQ', 'pjFDSoq2zOo', 'kQMsLTlkEqM', '0gH9qNaHHJE', 'y55_KgFts2Q', '6cTfl2Za7rU', 'NIG73862QzY', 'b1t5W9LLih8', 'qnZhf1crV9U', 'ITZpJY6K4wk', '_YprkiR8wBA', 'rBA6jcA_1Y4', 'Wf6ct1PTqBg', '4F1RV54nYro', 'HXA9zmm6eFQ', 'reoK3Rqt_Y0', 'E_ogC3r4N0Y', 'WqCVLEnggFY', 'levdzjNSPN4', 'gSsIUzRLHyU', 'Dl0HroHEVUc', '7WDfTG0F1jA', '1UQ5dJ1uCT4', 'MnAeyYEy2Ek', 'TbJkuPRKOr8', 'Ge2q4Q6yV0Y', 'AD5-xyS5zKs', 'kVMdXPHmnPQ', 'G7wWnmvHMj8', '9yYf3g9EaEU', 'JcDcCh0jJq0', 'r4diT2073mM', 'lV3pF1BWec4', 'k0JZBqnTUoQ', 'O-j2dhQdk44', '2SNwsfc6RVo', '7iN97oL9bqE', 'SxMW1pmXi70', 'S4yPS2NZkrU', '3DpOAsfQpXg', 'Uszz5oGYAbE', 'yx-hCyc-CpE', 'C9dTRS0cOAc', 'FcUtjX0txDA', 'B4OnUQEfDhA', 'GbPUgTN-paY', 'AQ2IC6KoCio', 'FzSTJq_fpv0', 'OUHXHhlymWw', '0hoetbRTmr8', 'GJnBufhoBc8', 'iJv7GN-5Kyc', 'mLZQUvV6N1w', '1o2SiI_Pgg4', 'jHJtgcLGT5Q', 'Dt8ZSKzSi1s', '5kONlEBLelM', 'b5FcdLujmNI', 'qzkNNSn7d1A', 'tbSxgiXOxHQ', 'TNrdwGvhAEw', 't2KeMDls3qk', '6n03S6XEZAM', 'hnMZm-Dgrk8', 'XLYd_QGQS1U', 'jriyXjT1ofE', '5DTOjpibz58', 'EVnUiEV8hO8', 'Y4ssar3pA8M', 'Z2N5b3uxwpc', 'Ee6GN66rm8A', 'O0wmlMQmdnU', 'ydN2-62s85o', 'kCGNRTnmJB0', '8IZNn3OABWk', 'AIuiN-Gy81E', 'd2TF6YdnTrU', 'DY6xVKmN41U', 'NRxJ3hHt4Ek', '9TVB8s6zjdI', 'o_d3hR4XlBU', '29YZRG35oPE', 'bP66ZPXIFP4', 'C0cAQ2ru9Fg', 'HUW2WIBVUJk', '-2jtMsQHTW4', 'IxeNQ6_gdlU', 'hHKilPAmDEU', '8OET5d5zhas', 'BBsPsVXBlPQ', 'mNXRbs2hA5o', 'gp-J9du6PhI', 'PqnM4WcU71g', 'mGPALmi7qFo', 'HyuAlk-Dofc', 'XPaXZ5_oKvQ', 'hQVNtXIy3B4', 'kjJva6Gf0VQ', 'dTXT7qORWJo', 'hTFcQYI2miY', 'wjRy7TDl8-g', 'UHwssMmjdRo', 'amq2vsrqLvk', 'ZB_deOu3yPw', '8puGqdJzJwk', '9id6rG_EcDo', '0ulZcOCA1kQ', 'SUvgQB3-JII', '1mLUoUkOEhw', 'YwrO8KmdEoE', '82wTWZpS6KA', 'VYi9TKDCY4w', 'PXsn8WkEonc', 'Hc1Bdai4GA0', 'VhENu8yLgVo', '8nuf1RFlJ5o', '4SeISmgBnic', 'iP1t7fNP-So', 'sL2EGDyh4cs', 'Ox9iSG8S6Zo', 'Em8RWkYC1bs', '1ppKfF7dCnU', 'SMqewkANMEg', '3d7DB4SXiO4', 'z5COibJdyXE', 'ob_lfEf1W2U', 'piTVD5hg9gg', '5iaGHMbBag0', 'k2U6TBdVpYg', 'GKcsRvT5-QE', 'sDQroJIVBdw', '4Z5nsbonOKo', 'gi24Xl2PJIc', 'jzDV02flhzs', 'a-d1SbczDNY', 'gQ-2jRDxPHw', 'sLm9zbGoli4', 'AtfiRS8TWIw', 'Drq9bG2Is3M', 'Fe_xe-rb2tM', 'l6VoUD_E-r0', 'ezKt8ftUykg', 'HloDI_4I4XE', 'gjcHNjq4rQU', 'B5XsWpmM3mQ', 'Q7e5SS3lw1s', 'pbekl2XlzLo', 'Dqg9-cZqVw0', 'u8KcctCDXeg', '_WNHHxl3LbQ', 'dKVmBTMZ-Eo', 'T4_a2Qy9OWs', 'l52e3qmwXFU', 'KKs20kxrva8', '2cO3SSN1-qc', 'hnZWslNgyVI', 'sE37HS0YkSU', 'hWmhjRTeH8E', 'ukqw6uw6Khw', 'Ih9g3L6EIXI', 'lUPbjlHDJN8', 'S_Ca158LEKY', 'kM13UVMKsEs', 'MFzaB2jknwk', 'CLterTjNDQM', 'BN1Gdi8kU1M', 'JzI7zLqQovo', '4sVuul5S51c', 'vAFvvFxgpeo', 'vDr74_wV3qo', 'psDt60SP_UI', 'IJm9rjIlwew', 'NiC4S0D4x9w', '3FJNJl8A4dA', '-KObTYIAlGI', 'GTPBQs6K1Ic', 'JVbnT8K9-cw', 'lbL9jhRW4gI', 'x1Ev_MOGavU', 'OvXwSbqC5-8', 'f1OgBKGnNuE', '7jlgwe33El8', '2jbRP7Ms1Gg', 'ui8HQg7dKWo', 'jysfiYxpxag', 'dBTYcTVYaaM', 'K_uL3N4UAYE', 'qxc3YRa52xE', 'RszeyCV_k9E', 'fPLvqajYUVA', 'Dl049l8_LVg', '_GqIdUaZ9jw', 'nw1AI9RjiWQ', 'GTKiFIIAcYY', '0lbalaygYKM', 'hAmD2KYhyEs', 'N7oJFUvJJEE', 'eFXq9vGqrVo', 'vDsWU1qV_0k', 'ALNsRWH4p2o', 'hp56eVrW9H0', '4KlBDJZfPiM', 'lyhlsmOCphE', '84_MXkDpT9c', 'DxShbwAMywk', 'l--RDZ2M02c', 'RLHD31lL30k', 'etFme4RtqHU', 'aadp6xDm6NI', '0GXZj7ZpQoM', 'PDdDCuhQAus', 'ccdXOAkY6K8', 'slNxj010iTs', 'b_PRAZVOPKU', 'lsLGdCoOIWg', 'kIV5E8NVtMI', 'HMHS5hZSttY', 'Sg_CpXW_jyQ', 'ySqUSxiIWjU', '3gnarKigGUk', 'DNCggFRtFjU', '3NzTtNd-3ps', '0MHBDarq27Y', 'EufoN9dLzcQ', 'BejhVLFW4Jc', 'hbMRv19SkXY', 'uonZ359GS9k', 'P1iHAm3pppM', 'lnIxGL_fP9E', 'qNVLV25-fpA', '56bSWR-VKEc', 'GmptOlRBWAQ', 'nVFNYlu3wUY', 'UqjGBhdBQB4', 'N0cCh-vXcLU', 'agGfgPjHPqY', 'wJ72yG5kkzQ', '_WvIWADgdQk', 'NpjdeX6Krgg', 'hUsI8fGBEJw', 'h9qmpVEFmX4', 'pne2gfr-kA8', 'iEFZMeuPc_8', '6qTOXbOU_4s', '6f2jANwqhJE', '4j9gWS1ZrpQ', 'YLu_MsWnGyM', '-1tZi-W25Dk', 'Jx7rVtJNy1o', '123htCaRF6g', 'q-AqKRwC_34', '1QD98TOWw-U', 'm5sminFcRKQ', '8W4bLxQAQgQ', 'hZfgUUKqAXk', 'ehj7EWO2uLE', 'fAI38QNDdOg', '7037po5Dl48', 'yb2zeW-mtYA', 'yXB82Ib3Evs', '8Klh4H_O1fg', '6iNoHASA8Nw', 'pHDBbGNQE0I', 'xxKC16YniBg', 'F4v-eNmWECw', '9afTMBAJZgk', 'eRUN1Z6RbEw', 'JYPGKHn7ErA', 'mXKIy9AMios', '-UbhrfPaZwI', 'bwJEF0HFTdg', 'tn1rN0tu1Ro', 'r0NrtWCux8g', 'kVgdUeLJUak', 'hWvnl95xAHI', '9QklWP-TptE', 'QCR0wyMbLes', 'owsBtnehXKU', 'FsNEasL2zp0', 'zQvXD5QlgQI', '6jezePkXuWA', 'rnSj3z1iw5U', '1OyMTBHgiNI', 'Y1JGY7ooEgQ', 'psM7zXvdg2s', 'h7CdnR8KIQk', 'X2uUXSEJHbE', 'Tz1VkMxRT_s', 'PEK6sjS9Ehs', 'wQZ-VeyOX5Y', 'ybp1BTQG05w', 'GU6eSTUxgdA', 'CpYKlg16D58', 'SIE1_sGzsN8', 'hHi4vAiA5lo', 'xTVXY_nn6ug', 'oXO7y0JaAzk', 'ZWkcix3Sz-E', 'oQlulThTa7A', 'B18vfSdAdLs', 'IxAmUVYH5RE', 'ZgbahaAG1HQ', 'fZTXvGo-ZdY', 'cayheNU39dw', 'rOmXHgbgDQI', '2dR1pmhgz2k', '6E5lfTicn6Y', 'CPnJHdCJ24I', 'Wu_Sb_jkr0s', 'Rp5QRKqrUAo', 'ugaGvXNdmhw', 'NwKWXDyRvMY', 'H2H_2LRHAUo', 'qD7g6Ot9bXo', '4Fof9JgjtSk', '_O6F0I0axlY', '_B4SKamoRG0', 's_jqz4uYNCs', 'ECBZlPqN_Z0', 'fmZK3vE_el4', 'Kx34V9RE59s', 'sdWeEhvqLBc', 'ctVu3iaQRr8', '5QlLzx_R3Fk', 'j-CZgSNYeRk', 'vEUTBblkFoQ', 'jhAyeFZPJi0', '_WUXlCbWdfQ', 'ujPsAcoSzHk', 'T7d23jBGToo', 'o2bc38WwBvQ', 'oGeoVigaw08', '4Rj2f_18bo4', 'Z_VGwnxcQtY', '3-Rb7l5FLZU', 'jb91cFnlVkg', 'i-uD2AZbuZs', 'i4Afqq2_O7k', 'p-r_TXqXGZQ', 'V9JsAX2MIyg', 'DFWtYetoP_I', 'RhkFxvAvvd0', 'fMx7-5EDErQ', 'nm2is67L_xY', 'MpIMyuk-Il8', '6kxg7jlaNo8', 'Ck3BgVGwHpo', 'eCbDfH8Oni4', 'Gr0iLB59BxU', '_7x-RvBAA1M', 'MLNDxyyL-AI', 'Mj4GIUSl7-c', '1M3tIKXCkUs', 'SoUH5V67qLg', 'g6oCHJtLOOo', '_GPtQbeWW5Q', 'pwpI3gL8SYw', 'm1cgoxoTulk', 'ohRZoFcd_gA', 'l1ydrXfFE0k', 'zM9jfgh3b2g', 'GzOrIbvYudI', 'FTnX0hFew6Q', 'uLvJ6YqBZIw', 'KWvKLvYreC4', 'ADHzilNFA3A', 'ijEWktp9OKk', 'fWjPDo0QO_0', 'QQGtk0917kE', 'FzpjHINVsIs', 'X34-iSrxiJc', 'j_gu1q9L1s8', 'LF3PZ6ewipg', 'faLRzPVRTvY', '0YQjsDJ0jww', 'S7iCKYpuj8s', 'S31jGrP2eM8', 'QZGrvJujDUo', 'VdTW5-ssfoE', 'Jz2gCdbHAMk', 'nBlY20m9dZw', 'MDyrOuPMJVw', 'AlPKbO3jUXg', 'Bgj4Fw-6kWA', '0ewPOycZLR4', 'Dj6PgunrQFA', 'eFXx0hu5dfo', 'gCawWTeGVeI', '8C8_kSDO-Gg', 'zfXXhjr5tyA', 'J5uY3JM-SLc', 'Vb4opm2gd0U', '5PD3S-LZkk4', 'JfVv8K4Z-Qg', 'w0_-DY1vCvc', 'ue4hFtuWpnw', 'wKcLHQJs4a4', 'BjCjePdowFc', 'vkOPJHnfibs', 'YV6UUvp35Mc', 'Bb3gcaNzdEM', 'vjLeTTtQo3M', 'SEIcy5vNf0U', '5hNZtseYru4', 'jucLS44iOkE', 'DxEdsyuUO6c', '3ZnE8kaTfsM', 'WRYPzhBNqoc', 'q92gk0izYVQ', '8eKzxvu84D0', 'BM6ox4DqL7M', 'h_STTlrip_k', 'nK4_QCeTRvA', 'xwvp1sJdVo4', 'pYIWyPVv9mY', 'DLE5W8wEpTQ', 'bRYs8evnt2w', 'uV4L3AhLcAA', 'Xbe7WuOT4Hg', 'lC4e8Uh_C-o', 'cRykZDnJbW4', 'uyi2RT3Kak4', 'Jpob_WQ3CQQ', 'NYkMFnDjr78', 'QP0ddb4b8zY', 'KjlkLYnxueU', 'yxu5ZfiZHSw', 'yRzpanrzrK4', 'ihQE_G_-PH8', 'TuSrNAtW8TA', '3sfGC7BcTSM', 'jPOoSz4Ab1A', '0oGLGq1I7E4', 'G7szSKp6DEw', 'F0RbvnNWgk4', 'oE4rCB9snAs', 'CbQ6fS8KumE', '5VoR9JNSuNw', '1r68LKWXx4M', 'M4nkwDAvRgc', '0CabVA4k1ns', 'Yz8-j2hWYbo', '43wx5y6OYTI', 'rj45JqmE6vU', 'cue_8Z7Lw9M', '-pWALFCg3Og', 'cKn4i2dvya0', 'E20Ljm5D7yU', 'CyXOX2_Hhf0', 'eyyho2-ErL8', 'iBpU9idmeVM', 'PV5a-blaM_M', 'i5-hbIrPaKs', '_oxx-cXDZbg', '64KFrJjunEY', '7Qf9cY4yk3g', 'ZJ9K2o4Rck8', 'yQT_TmfUzb8', 'U0DYJIRD-6U', 'KSgsat04lLk', 's-tYE79uyCk', 'MbDBr6j6sIQ', 'gLtC3a-sIkU', 'tL_kwTUG2Ag', 'MvoNVnjH0Xc', 'QdP28hMV3MI', 'kqtngPESsIU', '51qrUENkjMI', 'IglBJ62Sv3Q', 'joTn5hgyI0s', 'hbSY37dr45Y', 'zNVyU1X8mrA', 'i706ZlA3eSM', 'BkE9zNlNEsg', 'OLxbAW9Cid0', 'Q0px4Qwyrk0', '9eUoIuGJepg', 'G6sPG0n4R1o', 'aR6_cG7D5c8', 'lhGSR1iSsCY', '29hk00wFEoo', '_O2pKqX7Tzw', 'fnw14-fLoeY', 'JYdu6VgzRI0', '_YwrI5SlS8Q', 'Bo-dgSkNC-M', 'Yxigd9dlsd8', 'fq4RoLsa5gw', '_Fvee3MaAJg', '8t932519vyE', 'oERM7trctT8', 'eldpYwG3tEg', 'a7cUcKz-44s', 'aTqhMdQjLkI', 'V9YfnLGoJL8', 'ozhVcXVv9QQ', 'MTCkfcPlGOA', 'yUAgJ5GcnXQ', 'SrbmOCiHqRk', 'vp_mLVO35w8', 'QhohWWvpB7M', 'H6IoNSNnl0M', 'k_zBkqBTFtE', '1rXC2JJyHiw', '96Ol2RQNPSw', 'FGbvnLBUjKw', 'fAvaCJWf9TI', 'nDya4ooODQ8', 'zJg7j5ge9EM', '4iHiPrjeVcI', 'NLGoWEdZy2c', 'jSP-LV1ue10', 'J101G5AnGOg', 'NYi-7iaqmHk', 'OWl5PxRmw1w', 'tRuCbZf71h4', 'fi897xwV5Gk', 'FKO51klKNQw', 'cFB_p7Xif9M', 'DiDUSKTg3JU', 'iQhk_YZ27YA', 'OM3yCSjI4P4', 'wiXXrtye0NQ', 'rrhZoeNQTa0', 'tgnNgw1upyw', 'lVNc1CUTX_s', 'QPQG1hXKrgU', 'K9IqGyy9UnE', 'zbvO0S46W-0', 'quFRqt80l28', 'wIYLRDZEMzo', '5GvJqkDOgBI', 'Z7otAwjufF4', 'P-T3HKA0FRA', 'jDVbT2Hc-5Q', 'I-qoTGhdnJ4', 'gYcWA1v6Njs', 'i8zQtMUmRTM', 'UHOIaYOxKlI', '8rFsZvVb_xo', 'f5bRHHk0RvY', 'sro5NH4ELV0', '1v4h-i2N5KM', 'LgXHIfGsEnw', 'PlaQGL3VVBc', '1T-lBDKXTV8', 'n2TxR3bDrVk', 'FBRSiSjDOSU', 'thXstqQcdQ4', 'zl6BuEwLyLE', '4JBuW-Y0eQg', '-gqs2mTVSPQ', 'U8LCE8YPfic', 'LzrYwbFxkIc', 'T_OofJ8RmgU', 'hTBFFIgVbq4', '5kwa2T9qDrA', 'CPcNNzePZh4', 'qhCnB5QsEPM', 'Ec-ZTHgUF5A', '-toUdF5wWq4', 'q1PBDoRgiMQ', '-d8sNML3WT8', 'icJ9WNDWTSo', 'hiTQbEXWo7g', 'bSQHs0eC9Zw', 'TJ64ItDUDF0', 'sjKqFTBjpw8', 'DWiZGlNxoOA', 'YCzqSUR3l30', 'YyLcD7_vt0Q', 'f5XBlzi9-mI', 'U6Hi4vbekME', 'ZUQhxv7Anwo', 'nPE0GkSESU4', 'cNwnDW_9-3c', '1UdUcBaXvy8', 'vq2uxgWHhj0', 'y7Hu-8NhuJQ', 'wJxdEqQjr3M', 'R0BX3NzxjsY', 'zk1JKWAUOGU', 'UuU1ZrsNIO4', 'GK_X4jiR7WM', 'sbgWwg2Ykew', 'rMDRIGWolQA', 'tObbUX1gulo', 'SH73ocAu0DM', 'QqG-2_ceNX8', 'U0_6GdH8jWU', '8g17i73Ek_I', 'BB-UaywSp8Q', 'w9DNCBWV6qE', 'SJQKPXYRTBk', 'b3pXzVF-pyw', 'TM4ZDL60_F8', 'cG51q6CRRyw', 'cHJ9btr1QJI', 'SZyBcsGvBYM', 'ZSy8Ic_kSlo', 'bOXLFbofEZ0', 't91lX1pIXpQ', 'brWi7egHV8w', 'Rx70OYVqdEo', 'WhhovQ7HW4k', 'FPxzNEL8nzk', 'YVA2cd7T_to', 'eM-YjNHmM84', 'na_dBj-suvE', '7Vl9oU5UnTE', '8W1c4XnO4qk', '7PPctNhe99E', '9UiKdm2Yqd0', '-cRGIXzrzxA', 'EoztrLQkgew', 'nuiA6-36Mvk', 'Ygez4GCkDZU', 's8PLSGxWVbA', '0uzg-5tpaXI', 'BORVxbsdkCM', 'i8XG9HaS6Ek', 'Uv08g7LVjd0', 'R1XqbRCfefA', 'mU1IdB7rv70', 'OJdwQpR-FvY', 'R6DSMIkdfdI', 'xQWBQTmnMro', 'YIQfjcF39Ms', 'M7u7pRUXokk', 'tB46WSVuWnY', 'u4iqN_9Xt34', '_ahir4HVOHM', 'Y-58152x6JY', 'QXCfGFzYF6c', 'tWk0lDHQAJ4', 'AM2K20qtDZ8', 'zclclhg2TEI', 't_KgTaAsHLs', 'v02S6MEPFxA', 'lP_Erg2doCA', 'znxF94TnoT4', '6JMjUGp5kUU', 'iVBcVbx_HQA', 'JxSnVmJ6msM', 'elk3cObSTEs', 'sR8ADZOcPho', 'm8rDhS8y46g', 'nrB6AJOhpeY', 'M9twYdhUrFQ', '95_-ThLpbJ4', 

### 3.7 Handling Missing Values (Imputation)
Filling NaNs in text arrays, hashtags, and assigned Wikipedia topics.

In [49]:
df_dim_vids['primary_hashtag'] = df_dim_vids['primary_hashtag'].fillna('No primary hashtag')
df_dim_vids['tags'] = df_dim_vids['tags'].fillna('No tags mentioned')

In [50]:
df_dim_vids.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7841 entries, 0 to 7840
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   video_id               7841 non-null   object
 1   title                  7841 non-null   object
 2   duration_seconds       7841 non-null   int64
 3   view_count             7841 non-null   int64
 4   like_count             7841 non-null   int64
 5   comment_count          7841 non-null   int64
 6   tags                   7841 non-null   object
 7   is_hd                  7841 non-null   object
 8   licensed_content       7841 non-null   object
 9   made_for_kids          7841 non-null   object
 10  audio_language         7841 non-null   object
 11  content_rating         7841 non-null   object
 12  embeddable             7841 non-null   object
 13  public_stats_viewable  7841 non-null   object
 14  topic_categories       6783 non-null   object
 15  has_captions           7841 non-null   object
 16  primary_hashtag        7841 non-null   object
 17  content_type           7841 non-null   object
 18  published_date         7841 non-null   datetime64[ns]
 19  published_time         7841 non-null   object
 20  duration               7841 non-null   object
dtypes: datetime64[ns](1), int64(4), object(16)
memory usage: 1.3+ MB

In [51]:
df_dim_vids.rename(columns={'topic_categories': 'assigned_wiki_topic'}, inplace = True)
df_dim_vids['assigned_wiki_topic'] = df_dim_vids['assigned_wiki_topic'].fillna('No wiki topic assigned')
df_dim_vids['assigned_wiki_topic'].unique().tolist()

['https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Politics',
 'https://en.wikipedia.org/wiki/Politics, https://en.wikipedia.org/wiki/Society',
 'No wiki topic assigned',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Technology',
 'https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Military',
 'https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Politics, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Health',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Knowledge',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Food',
 'https://en.wikipedia.org/wiki/Business',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Knowledge',
 'https://en.wikipedia.org/wiki/Video_game_culture',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Politics',
 'https://en.wikipedia.org/wiki/Entertainment',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Military',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Pet, https://en.wikipedia.org/wiki/Politics',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Politics',
 'https://en.wikipedia.org/wiki/Association_football, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/American_football, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Politics',
 'https://en.wikipedia.org/wiki/American_football, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Health',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Technology',
 'https://en.wikipedia.org/wiki/Knowledge, https://en.wikipedia.org/wiki/Technology',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Physical_fitness',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Fashion, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Fashion, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Technology',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Physical_fitness',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Film',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Physical_fitness',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Food',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Performing_arts',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Performing_arts',
 'https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Technology',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Fashion, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Military',
 'https://en.wikipedia.org/wiki/Politics, https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Knowledge, https://en.wikipedia.org/wiki/Military',
 'https://en.wikipedia.org/wiki/Fashion',
 'https://en.wikipedia.org/wiki/Fashion, https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Fashion, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet, https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Religion, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Film, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Military',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/American_football, https://en.wikipedia.org/wiki/Association_football, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Fashion, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Military',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Motorsport',
 'https://en.wikipedia.org/wiki/Music',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Hip_hop_music',
 'https://en.wikipedia.org/wiki/Association_football, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Military',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Politics, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Video_game_culture',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Health',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Military',
 'https://en.wikipedia.org/wiki/Jazz, https://en.wikipedia.org/wiki/Music',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Physical_fitness',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Fashion',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Hobby',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Technology',
 'https://en.wikipedia.org/wiki/Music, https://en.wikipedia.org/wiki/Music_of_Latin_America',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Cricket, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Cricket, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Religion',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Military',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Jazz, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Physical_fitness, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Golf, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Professional_wrestling',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Film',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Technology',
 'https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Politics',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology)',
 'https://en.wikipedia.org/wiki/Fashion, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Fashion, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet, https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Golf',
 'https://en.wikipedia.org/wiki/Fashion, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Military',
 'https://en.wikipedia.org/wiki/Baseball, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Pet, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Mixed_martial_arts, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Technology',
 'https://en.wikipedia.org/wiki/Motorsport, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Motorsport',
 'https://en.wikipedia.org/wiki/Politics, https://en.wikipedia.org/wiki/Religion, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Music',
 'https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Mixed_martial_arts, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Action_game, https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Video_game_culture',
 'https://en.wikipedia.org/wiki/Association_football, https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Knowledge',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Physical_fitness',
 'https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Film, https://en.wikipedia.org/wiki/Motorsport',
 'https://en.wikipedia.org/wiki/Action_game, https://en.wikipedia.org/wiki/Video_game_culture',
 'https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Motorsport, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Action-adventure_game, https://en.wikipedia.org/wiki/Action_game, https://en.wikipedia.org/wiki/Video_game_culture',
 'https://en.wikipedia.org/wiki/Motorsport, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Basketball, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Boxing, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Mixed_martial_arts',
 'https://en.wikipedia.org/wiki/Golf, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Tennis',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Pop_music',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Performing_arts, https://en.wikipedia.org/wiki/Professional_wrestling',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Knowledge',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Knowledge, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Television_program, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Military, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Technology, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Politics, https://en.wikipedia.org/wiki/Society, https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Television_program, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Film, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Entertainment, https://en.wikipedia.org/wiki/Performing_arts, https://en.wikipedia.org/wiki/Professional_wrestling, https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Sport, https://en.wikipedia.org/wiki/Tennis',
 'https://en.wikipedia.org/wiki/Humour, https://en.wikipedia.org/wiki/Politics, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Physical_fitness, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Tourism',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Health, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Physical_fitness',
 'https://en.wikipedia.org/wiki/Music, https://en.wikipedia.org/wiki/Politics',
 'https://en.wikipedia.org/wiki/Golf, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Pet',
 'https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Hobby, https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Motorsport, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Food, https://en.wikipedia.org/wiki/Television_program',
 'https://en.wikipedia.org/wiki/Lifestyle_(sociology), https://en.wikipedia.org/wiki/Tourism, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Film',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Religion, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Boxing, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Humour, https://en.wikipedia.org/wiki/Society',
 'https://en.wikipedia.org/wiki/Motorsport, https://en.wikipedia.org/wiki/Sport, https://en.wikipedia.org/wiki/Vehicle',
 'https://en.wikipedia.org/wiki/Boxing, https://en.wikipedia.org/wiki/Mixed_martial_arts, https://en.wikipedia.org/wiki/Sport',
 'https://en.wikipedia.org/wiki/Business, https://en.wikipedia.org/wiki/Tourism',

### 3.8. Exporting the current df_dim_vids as CSV for future fact table making :

In [52]:
df_fact_vids = df_dim_vids[['video_id', 'tags', 'assigned_wiki_topic']]
df_fact_vids.to_csv('fact_vids.csv', index=False)

### 3.9. Preparing df_dim_vids for exporting by removing the column which belong to fact table for more preparation :

In [53]:
df_dim_vids.drop(columns ={'tags', 'assigned_wiki_topic'}, inplace = True)
df_dim_vids.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7841 entries, 0 to 7840
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   video_id               7841 non-null   object
 1   title                  7841 non-null   object
 2   duration_seconds       7841 non-null   int64
 3   view_count             7841 non-null   int64
 4   like_count             7841 non-null   int64
 5   comment_count          7841 non-null   int64
 6   is_hd                  7841 non-null   object
 7   licensed_content       7841 non-null   object
 8   made_for_kids          7841 non-null   object
 9   audio_language         7841 non-null   object
 10  content_rating         7841 non-null   object
 11  embeddable             7841 non-null   object
 12  public_stats_viewable  7841 non-null   object
 13  has_captions           7841 non-null   object
 14  primary_hashtag        7841 non-null   object
 15  content_type           7841 non-null   object
 16  published_date         7841 non-null   datetime64[ns]
 17  published_time         7841 non-null   object
 18  duration               7841 non-null   object
dtypes: datetime64[ns](1), int64(4), object(14)
memory usage: 1.1+ MB

### 3.10 Final Validation & Export
Reviewing the cleaned dataset and exporting to a clean CSV file.

In [54]:
df_dim_vids.head()

,video_id,title,duration_seconds,view_count,like_count,comment_count,is_hd,licensed_content,made_for_kids,audio_language,content_rating,embeddable,public_stats_viewable,has_captions,primary_hashtag,content_type,published_date,published_time,duration
0,WruHZnB_srw,#Tech #stocks drop after reports say #OpenAI f...,71,17985,429,23,HD,licensed,not for kids,English (United States),not age-restricted,embeddable,stats visible,has no caption,No primary hashtag,Standard Video,2026-04-28,19:46:26,00:01:11
1,BDqhOhr-orw,The Rise And Fall Of 7 American Businesses,12634,26268,408,24,HD,licensed,not for kids,English (United States),not age-restricted,embeddable,stats visible,has no caption,#USbusinesses,Standard Video,2026-04-28,19:45:00,03:30:34
2,r3p0R9dlKww,"Priced at $209M, the MQ-25 #Stingray is design...",62,73649,941,55,HD,licensed,not for kids,English (United States),not age-restricted,embeddable,stats visible,has no caption,No primary hashtag,Standard Video,2026-04-27,22:14:47,00:01:02
3,Gv8mItBLZ5Y,From alleged hairdryer hacking to insider #tra...,84,6282,76,3,HD,licensed,not for kids,English (United States),not age-restricted,embeddable,stats visible,has no caption,No primary hashtag,Standard Video,2026-04-27,19:47:02,00:01:24
4,dKoIepQtPO8,Footage shows moments after security detains #...,54,7491,88,11,HD,licensed,not for kids,English (United States),not age-restricted,embeddable,stats visible,has no caption,No primary hashtag,Short,2026-04-26,15:49:48,00:00:54

In [55]:
df_dim_vids.to_csv('dim_vids_clean.csv', index=False)

# Phase 4: Processing the Fact Table
### 4.1 Fact Table Initialization
Preparing the transactional fact metrics (views, likes, comments).

In [56]:
df_fact_vids = pd.read_csv('fact_vids.csv')

### 4.2. Explode all assigned wikipidia URLs of topics to have one in each row for more better practices:

In [57]:
df_fact_vids['assigned_wiki_topic'] = df_fact_vids['assigned_wiki_topic'].str.split(', ')
df_fact_vids = df_fact_vids.explode('assigned_wiki_topic')

In [58]:
df_fact_vids.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12666 entries, 0 to 7840
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   video_id             12666 non-null  object
 1   tags                 12666 non-null  object
 2   assigned_wiki_topic  12666 non-null  object
dtypes: object(3)
memory usage: 395.8+ KB

### 4.3. remove the URLs path and leave only the assigned topic part from wikipedia URLs :

In [59]:
df_fact_vids['assigned_wiki_topic'] = df_fact_vids['assigned_wiki_topic'].str.split('/').str[-1].str.strip()

### 4.4. Explode all tags to have one in each row for more better practices :

In [60]:
df_fact_vids['tags'] = df_fact_vids['tags'].str.split(', ')
df_fact_vids = df_fact_vids.explode('tags')
df_fact_vids['tags'] = df_fact_vids['tags'].str.strip()

In [61]:
df_fact_vids.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93873 entries, 0 to 7840
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   video_id             93873 non-null  object
 1   tags                 93873 non-null  object
 2   assigned_wiki_topic  93873 non-null  object
dtypes: object(3)
memory usage: 2.9+ MB

In [63]:
df_fact_vids.to_csv('fact_vids_clean.csv', index = False)